### ISSUE TITLE
Question about security of safetensors

### ISSUE THREAD

**Issue by User1231300** [huggingface/safetensors#112]
I realize I might have created a post in the wrong section, so I'll redo it here:

Hi, coming from a non-IT field I would like to ask the owner of the code if they could spend a couple words talking about the security of this new format.

In simple words, what does it mean that this format is safe?

Does it mean I can convert any malicious .ckpt model that I find and once it is .safetensors it can't infect my machine anymore? Or is this format only protecting against some kinds of threats? if so, which ones? How concerned should I be running randomg converted .ckpts found over the internet once they are made .safetensors?

**Comment by Narsil** [comment]
Let's keep the discussion here if you don't mind: https://github.com/huggingface/safetensors/discussions/111

Closing this.
