### ISSUE TITLE
Converting back to pickle (PyTorch)

### ISSUE THREAD

**Issue by JustMaier** [huggingface/safetensors#120]
I know, security and going backwards and all, but I'm looking into this to offer support to SD clients that don't yet support safetensors.

My plan is to convert SD models into both formats so that users can use which works for them. So PyTorch pickles would be converted to safetensors and vis-versa. Both files would be available for users.

Is this conversion currently possible?
I scanned the existing issues and since I'm not very versed in python I couldn't tell at first glance if this had already been answered.

**Comment by Narsil** [comment]
Sure

```python
Weights = load_file(filename, device ="cpu")
With open(filename, "rb") as f:
    Torch.save(weights, f)
```

**Comment by JustMaier** [comment]
Haha. That easy eh, guess that shows just how little I know how the internals of this stuff works.
