### ISSUE TITLE
Is this compatible with Invoke AI?

### ISSUE THREAD

**Issue by brunsonator3** [huggingface/safetensors#136]
Invoke won't let me use safetensors. Do I need to use this code? Or am I just doing something wrong?

**Comment by Narsil** [comment]
It's coming if I read this correctly:

https://github.com/invoke-ai/InvokeAI/pull/1583

Basically this PR needs to be merged:

https://github.com/invoke-ai/InvokeAI/issues/1813

And then it will be useable by default (`diffusers` works by loading `safetensors` if it's available both on the repo AND the library being there).

Were you thinking about enforcing the use of the format? If yes, we would need to take it to diffusers to maybe add a flag for this.
`diffusers` is probably willing to do this, the main thing we try at HF not to do is to do breaking change which would break existing user's code.

**Comment by DrakenZA** [comment]
a safetensor ckpt is different from safetensor diffuser format though.

I believe most people are looking for the ckpt safetensor support, which will be separate from diffuser models.

**Comment by Narsil** [comment]
> a safetensor ckpt is different from safetensor diffuser format though.

You mean StableDiffusion ckpt kind of file ? Then it's already supported by the Webui https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_models.py#L168-L179 

Does that help ?

**Comment by DrakenZA** [comment]
Ya but i mean safetensor ckpt support in InvokeAI.

**Comment by keturn** [comment]
I think InvokeAI does support single-file safetensor models by now, and this issue can be safely closed.

**Comment by Narsil** [comment]
Thanks @keturn 

Closing this then
