### ISSUE TITLE
Can't convert in colab anymore

### ISSUE THREAD

**Issue by User1231300** [huggingface/safetensors#146]
Hello again.

I've been using this colab you provided to a user a while ago to convert my models online:

https://colab.research.google.com/drive/1YYzfYZEJTb3dAo9BX6w6eZINIuRsNv6l#scrollTo=Tq4DxOmTwr2M

But lately i'm not able to do it anymore. For example, changing the wget to this model: https://huggingface.co/darkstorm2150/Protogen_v2.2_Official_Release/resolve/main/Protogen_V2.2.ckpt i get this error:

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[<ipython-input-3-04b9db9c92d0>](https://localhost:8080/#) in <module>
      1 import torch
----> 2 weights = torch.load("/content/Protogen_V2.2.ckpt")["state_dict"]

KeyError: 'state_dict'

If i remove the state_dict it seems to work fine. I don't know what it does tho. Should I remove it? Thank you

**Comment by Narsil** [comment]
This key `state_dict` depends on how the models were saved.

Try just using this:

```python
weights = torch.load("/content/Protogen_V2.2.ckpt")
```

For full check, actually look at the data contained by looking at `weights.keys()` to see if it's the model directly or something else.

**Comment by User1231300** [comment]
Thank you for your answer @Narsil. And happy holidays.

#For full check, actually look at the data contained by looking at weights.keys() to see if it's the model directly or something else.

I did this. I'm not really savy. Is there some easy heuristics for what I should look out for?

**Comment by Narsil** [comment]
You are looking for a dict with string as keys and tensors as keys.
