### ISSUE TITLE
What's the expected usage of `metadata` when saving a Dict with tensors?

### ISSUE THREAD

**Issue by alvarobartt** [huggingface/safetensors#147]
Hi again @Narsil!

So after playing around for quite a bit with `safetensors` I wanted to ask you what's the intended purpose of storing the `metadata` during `save` (assuming it's just informative data), as it's not loaded back when calling `load`, so that's lost unless you manually check the file as that's readable-text.

Thanks for your work and help!

**Comment by alvarobartt** [comment]
Here's an example of how I'm actually using it:

```python
from safetensors.flax import save

encoded_bytes = save(tensors=tensors, metadata={"tensors": "Tensors contain embeddings previously generated with MiniLM.", "url": "https://huggingface.co/sentence-transformers/all-MiniLM-L12-v2"})
```

So that then when I load those back either from a `tensors.safetensors` file or from buffer from `encoded_bytes`, I see that the metadata is either lost (or I'm not able to access it):

```python
from safetensors.flax import load

decoded_bytes = load(tensors=encoded_bytes)
```

Is metadata intended to be loaded when calling `load`? Am I missing something and `metadata` is somewhere?

**Comment by alvarobartt** [comment]
So more context, `__metadata__` is lost when calling https://github.com/huggingface/safetensors/blob/dc891f56afc61fbbbc2e804ad8ed156a0798a75c/bindings/python/src/lib.rs#L154 before actually loading the tensors, I don't know if there's an easy workaround or whether this is the intended usage of `metadata`, but I can help if needed.

**Comment by Narsil** [comment]
Hello, it's actually available this way: 

```python
with safe_open("model.safetensors", framework="pt") as f:
    print(f.metadata())
```

`load_file` is usually a small wrapper over `safe_open` (with less features).

**Comment by alvarobartt** [comment]
Hi @Narsil that's nice to know, I'll probably change some things in `safejax` to make it work also with metadata, otherwise I'll just skip the `metadata` for now

**Comment by alvarobartt** [comment]
@Narsil also regarding `safetensors.flax.save` and `safetensors.flax.load` is there any way to load the `metadata` when stored as bytes and not in a safetensors file? Or in that concrete case the `metadata` is ignored? Thanks

**Comment by Narsil** [comment]
It's currently ignored yes.

Could you provide a bit more information on your end use case ?

Currently, the idea is that `load` and `save` have already allocated the memory of the tensors, and just like `load_file` and `save_file` the metadata at such a high level is not what you are looking for (only the tensors are returned).`safe_open` is the actual interface that provides all the features needed.

For in-memory representation, maybe a new function like `load_metadata` could be written. But in concrete cases that might mean multiple reads of the header, so maybe there's a better way to align with something like `safe_open` that makes sense, and wouldn't explode code complexity.

**Comment by alvarobartt** [comment]
Hi again @Narsil, as you may know, I'm building [`safejax`](https://github.com/alvarobartt/safejax) (is already stable BTW), to easily serialize JAX (Flax, Haiku, and Objax) model params using `safetensors`, and ideally, I support both load and save to/from bytes, and to/from safetensors file, but I wanted to include also the `metadata` option so as to align `safejax.serialize` and `safejax.deserialize` with both `save`/`save_file` and `load`/`load_file`, respectively.

So I wanted to also allow the retrieval of the dumped `metadata` during `save`/`save_file` with `load`/`load_file`, anyway, if the option is to use `safe_open` I can just put a warning message so as to mention that when saving metadata, it can only be retrieved back using `safe_open` (which is going to replace `load_file` in `safejax`), so I don't think there's need to define `load_metadata` function IMO, but up to you.

Thanks as always!

**Comment by Narsil** [comment]
I see. I'll look into maybe something like `safe_read`. (which would be like `safe_open` but for a regular buffer).

Can't promise anything, but if it can come as no extra code, that would be ideal.
