### ISSUE TITLE
Flaw in the format design: lack of signature and version information

### ISSUE THREAD

**Issue by KOLANICH** [huggingface/safetensors#152]
This format has a flaw, it lacks a signature, using which one can detect
* that a file is a safetensors collection even if it has wrong filename extension
* detect safetensors collections embedded into other formats without knowing their structure.
* identify format version

We can fix it in a backward-compatible way. We can state that the JSON of the header must start with exactly the following
```json
{
	"__metadata__": {
		"safetensors": [
```

(`lf` line endings)

As metadata is by default arbitrary, parsing such tensors won't cause failure on the legacy implementations. Newer implementations must serialize format version into `__metadata__.safetensors` as an array of 3 semver integers.

Signature scanners can scan for exactly this prefix, then go back by 8 bytes, and try to parse the format. Libraries MUST ensure that the prefix is present with all the whitespaces. If the JSON-serializing lib doesn't emit it, it is easy to fix: just cut the prefix emitted by the lib and then replace with our static prefix with the whitespaces.

For compatibility, when parsing libs MUST NOT fail if the prefix is not exactly this, but can emit a warning.

**Comment by Narsil** [comment]
I understand why you're saying this, and your idea for including a file version format is definitely what I had in mind when `__metadata__` was included. 

However, I don't feel this is a necessity right now.

I don't think it's necessary to change the spec of the format, any time soon, and as long as readers don't need to do anything differently based on a specific version, I'm not sure there's a need to include a version number. And if there was something different to be done, it's not exactly a clear cut imo if including version numbers in files has any benefit over having a completely different format.

Like JSON doesn't have a version number. That doesn't prevent YAML, TOML, or any other formats to co-exist.

**Comment by KOLANICH** [comment]
>it's not exactly a clear cut imo if including version numbers in files has any benefit over having a completely different format.

It's true. BTW I'm not sure how this format is better than just a bunch of `numpy` `npy` files within a `tar`ball or an uncompressed archive. `zip` and `tar` archives have quite some ecosystem around them, this format has none.

Maybe it is not too late to just discard this format, rewrite the lib to read both the legacy one and the new one, but write only the new one, convert all the files on the HuggingFace hub in the new more compatible one and then after some time just drop the code reading the legacy one?

**Comment by akx** [comment]
As touched upon in https://github.com/huggingface/safetensors/pull/306#issuecomment-1663026860, with #306 we now specify that the first byte of the header must be `{`. For new, incompatible versions, we can thus specify that that byte must be something else.

**Comment by Narsil** [comment]
No that byte doesn't have to change.
