### ISSUE TITLE
Prebuilt package for m1/apple silicon

### ISSUE THREAD

**Issue by remixer-dec** [huggingface/safetensors#153]
Is there a way to install this on M1/arm64 mac without installing the rust compiler?
<summary>Pip error</summary>
<details>
Collecting safetensors
  Using cached safetensors-0.2.7.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: safetensors
  Building wheel for safetensors (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for safetensors (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-38
      creating build/lib.macosx-11.0-arm64-cpython-38/safetensors
      copying py_src/safetensors/__init__.py -> build/lib.macosx-11.0-arm64-cpython-38/safetensors
      copying py_src/safetensors/numpy.py -> build/lib.macosx-11.0-arm64-cpython-38/safetensors
      copying py_src/safetensors/tensorflow.py -> build/lib.macosx-11.0-arm64-cpython-38/safetensors
      copying py_src/safetensors/torch.py -> build/lib.macosx-11.0-arm64-cpython-38/safetensors
      copying py_src/safetensors/flax.py -> build/lib.macosx-11.0-arm64-cpython-38/safetensors
      running build_ext
      running build_rust
      error: can't find Rust compiler
</details>

<summary>Conda error</summary>
<details>
PackagesNotFoundError: The following packages are not available from current channels:

  - safetensors

Current channels:

  - https://conda.anaconda.org/huggingface/osx-arm64
  - https://conda.anaconda.org/huggingface/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

</details>

**Comment by Narsil** [comment]
Python 3.8 is not offically supported by MacOS M1 (afaik). That's the reason it's not prebuilt.

But since I've seen the issue being open in a couple of projects, how did you get to install python 3.8 on M1  ?

**Comment by remixer-dec** [comment]
I'm pretty sure python 3.8 was installed as a built-in software in macos itself. There is also a [homebrew package](https://formulae.brew.sh/formula/python@3.8) and a [miniconda](https://docs.conda.io/en/latest/miniconda.html) variation.  A lot of packages on pip [support](https://pypi.org/project/Pillow/#copy-hash-modal-9315caee-c459-4be8-9048-6017624f4632) python 3.8 and 3.7 wheels form macos_arm64.

I realize that support for these versions is getting less and less, which causes compatibility issues, especially with type definitions, even though two years ago these versions were recommend as the most stable and supported, so maybe it is a good idea for me to upgrade python and all the installed dependencies, but with limited storage space and Internet speed, it is not that easy.

**Comment by Narsil** [comment]
This is super weird, I was sure to have tested it couldn't be done.

Could have been a GH runner limitation, or support wasn't there, or just buggy at start. But I can't figure it out now.
Trying to add support for it now since you are correct it should be possible. Will report if anything goes wrong.

For future me in case you are going insane twice, python 3.7 is not supported at this time :)
https://doesitarm.com/formula/python@3.7/
Reports that no, it does not support 3.7 yet.

**Comment by Narsil** [comment]
Should be good now, can you confirm (on safetensors==0.2.8)

**Comment by remixer-dec** [comment]
Now it works, thank you!

**Comment by ylhsieh** [comment]
I am faced with the same issue for python 3.9 and conda. Which python version is pre-built? Maybe I will just create another environment and install there?

**Comment by Narsil** [comment]
Should be released for all versions: https://github.com/huggingface/safetensors/blob/main/.github/workflows/python-release-conda.yml

However I'm not sure how conda works on M1. Can't you install with `pip`?

**Comment by ylhsieh** [comment]
Yes pip worked, thanks! Probably conda is not building arm64 binaries?
