### ISSUE TITLE
Handle to model file remains open after `safe_open` goes out of scope?

### ISSUE THREAD

**Issue by space-nuko** [huggingface/safetensors#164]
Hi, I want to read the metadata and tensors of a `.safetensors` file, update the metadata and write the file back (overwriting the original). I tried to do that with this code:

```python3
#!/usr/bin/env python

import sys
import os.path
import safetensors.torch

model_path = sys.argv[1]
if not model_path:
    print("Provide a model path.")
    exit(1)

if not os.path.splitext(model_path)[1] == '.safetensors':
    print("Must be .safetensors file.")
    exit(1)

tensors = {}
metadata = {}
with safetensors.torch.safe_open(model_path, framework="pt") as f:
  metadata = f.metadata()
  for k in f.keys():
    tensors[k] = f.get_tensor(k)

safetensors.torch.save_file(tensors, model_path, metadata)
```

But I get this error:

```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-scripts\tset.py", line 24, in <module>
    safetensors.torch.save_file(tensors, model_path, metadata)
  File "C:\stable-diffusion-webui\extensions\sd-scripts\venv\lib\site-packages\safetensors\torch.py", line 71, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
Exception: Error while serializing: IoError(Os { code: 1224, kind: Uncategorized, message: "The requested operation cannot be performed on a file with a user-mapped section open." })
```

I expect that the handle is closed when `safe_open` goes out of scope. I'm not using the "GPU fast load" option set by an envvar either

Also if I wait before the program exits and try to delete the file Explorer won't let me, I checked with LockHunter and it says no process is using the file

So if I use `safe_open` on several model files in a program they all get locked until the program exits

I am on Windows 10, using safetensors 0.2.8 from pip

**Comment by Narsil** [comment]
> I expect that the handle is closed when safe_open goes out of scope. I'm not using the "GPU fast load" option set by an envvar either

This is not necessarily true since PyTorch keeps the memory map around (actually it's the one creating it with torch.Storage).

What you could try to do is cloning your tensors when you get them. It's going to cause extra memory usage, but will remove the need for the Storage handle that PyTorch keeps around.

```python
    tensors[k] = f.get_tensor(k).clone()
```

Does that work for you ?

What is intriguing though it that this issue does not arise on Linux... I'm not sure what to say since this almost pure torch code (`safetensors` is a small wrapper on top for such use cases).

**Comment by space-nuko** [comment]
I tried `.clone().detach()`, `.detach().clone()` and `.clone()` and none of them worked. Even just putting `pass` in the body of the `with` statement still causes the same error

**Comment by space-nuko** [comment]
Okay so with some further testing using the pure torch code, the same issue happens without using `safetensors` at all. But this only happens if the model has any tensors. If there are no tensors then I can save the metadata repeatedly with each invocation of the script

```python3
#!/usr/bin/env python

import sys
import os.path
from decimal import Decimal
import safetensors.torch
import mmap
import torch
import json
import os
import pprint

model_path = sys.argv[1]
if not model_path:
    print("Provide a model path.")
    exit(1)

if not os.path.splitext(model_path)[1] == '.safetensors':
    print("Must be .safetensors file.")
    exit(1)


def load_file(filename, device):
    with open(filename, mode="r", encoding="utf8") as file_obj:
        with mmap.mmap(file_obj.fileno(), length=0, access=mmap.ACCESS_READ) as m:
            header = m.read(8)
            n = int.from_bytes(header, "little")
            metadata_bytes = m.read(n)
            metadata = json.loads(metadata_bytes)

    size = os.stat(filename).st_size
    storage = torch.ByteStorage.from_file(filename, shared=False, size=size).untyped()
    offset = n + 8
    md = metadata["__metadata__"]
    return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}, md


DTYPES = {"F32": torch.float32, "F16": torch.float16}
device = "cpu"


def create_tensor(storage, info, offset):
    dtype = DTYPES[info["dtype"]]
    shape = info["shape"]
    start, stop = info["data_offsets"]
    return torch.asarray(storage[start + offset : stop + offset], dtype=torch.uint8).view(dtype=dtype).reshape(shape)


weights, metadata = load_file(model_path, device)
print(weights.keys())
pprint.pp(metadata)
nex = metadata.get("tes", "")
nex += "abc"
metadata["tes"] = nex

safetensors.torch.save_file(weights, model_path, metadata)
```

**Comment by space-nuko** [comment]
Okay so if I add `.clone().detach()` to the return value of `create_tensor` the code above works. Unfortunately I can't use the code verbatium in a stable-diffusion-webui extension because they use torch 1.12.1 and it seems there are some methods missing there (`.untyped()`). And the extension uses `load_file` elsewhere so the model file will get locked eventually anyway

**Comment by Narsil** [comment]
The fact that it uses `torch.Storage`  *is* what makes it fast. (Since it memory maps the files hence the tensors).

Another way, is maybe you could save into another file instead of the same ?

**Comment by space-nuko** [comment]
> Another way, is maybe you could save into another file instead of the same ?
And swap the thing afterwards ? (So dropping all the tensors, and reloading them from the new file)

How would I go about "dropping all the tensors"? I tried `.clone().detach()` and then `del f.get_tensor(k)` but that doesn't work. I thought that's what happened when the `with` goes out of scope

And I tried `del f` and that doesn't work either

Anyway if I try to save the model to a new file and just `os.replace()` the old file this happens:

```
Traceback (most recent call last):
  File "c:\stable-diffusion-webui\extensions\sd-scripts\tset.py", line 31, in <module>
    os.replace(model_path + ".2", model_path)
PermissionError: [WinError 5] Access is denied: 'C:\\stable-diffusion-webui\\train-lora\\aaaa.safetensors.2' -> 'C:\\stable-diffusion-webui\\train-lora\\aaaa.safetensors'
```

**Comment by Narsil** [comment]
I tried this with success it seems:
```python

tensors = {}
metadata = {}
with safetensors.torch.safe_open(test_path, framework="pt") as f:
  metadata = f.metadata()
  for k in f.keys():
    tensors[k] = f.get_tensor(k).clone()

safetensors.torch.save_file(tensors, f"{test_path}.out2" , metadata)
del tensors
shutil.copy(f"{test_path}.out2", test_path)
```

**Comment by space-nuko** [comment]
With that code I get this error:

```
./venv/Scripts/activate & python tset.py "C:\stable-diffusion-webui\train-lora\123124.safetensors"
Traceback (most recent call last):
  File "c:\stable-diffusion-webui\extensions\sd-scripts\tset.py", line 27, in <module>
    shutil.copy(f"{model_path}.out2", model_path)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'C:\\stable-diffusion-webui\\train-lora\\123124.safetensors'

```

**Comment by Narsil** [comment]
Try using a simple local path (without `C:\\` ) I think it's a `shutil.copy` thing, I had the issue too, but it worked when I worked with simpler paths.

Maybe `shutil.copyfile` works better?  https://docs.python.org/3/library/shutil.html#shutil.copyfile (seems more appropriate)

**Comment by space-nuko** [comment]
Yeah, it seems to work. I think I got it working in the extension too. Thanks for all your help

I think it would be very helpful to put a notice in the README or wiki that references to loaded tensors should be `del`ed if you want to modify the mode.

**Comment by Narsil** [comment]
Yes, thanks to you I found a deeper reason for this. And I'm working on fixing it so that you don't even have to do all that work.
It wasn't pytorch holding the file but `safetensors` itself.

https://github.com/huggingface/safetensors/pull/166

**Comment by Narsil** [comment]
Ok, so now with the PR I can get away with *almost* the original script, but you do need to `.clone()` the tensors so that Pytorch doesn't keep the mapping of the file.

```
# The extra "&" was needed in VSCode terminal, not sure about other terminals, it's not necessary in Bash linux for instance
pip install -e git+https://github.com/huggingface/safetensors#egg=safetensors"&"subdirectory=bindings/python
```

And then. 
```python
#!/usr/bin/env python

import sys
import os.path
import safetensors.torch

model_path = sys.argv[1]
if not model_path:
    print("Provide a model path.")
    exit(1)

if not os.path.splitext(model_path)[1] == '.safetensors':
    print("Must be .safetensors file.")
    exit(1)

tensors = {}
metadata = {}
with safetensors.torch.safe_open(model_path, framework="pt") as f:
  metadata = f.metadata()
  for k in f.keys():
    tensors[k] = f.get_tensor(k).clone()    # <----------------------MODIFIED HERE

safetensors.torch.save_file(tensors, model_path, metadata)
```

And this works.

I'm not sure how to make this even better tbh.. torch.Storage is what makes it fast so cloning by default defeats that purpose.

**Comment by vladmandic** [comment]
@Narsil @space-nuko 

I was working on a totally unrelated item, but stumbled upon this so though to share - `safetensors` will hold a lock since it uses `mmap` on a model file **if** file is loaded using `safetensors.torch.load_file`. but you can skip that completely and open a file directly and still use safetensors - in this case it will stream-load instead of doing mmap:

```python
with open(file_name,'rb') as f:
    buffer = f.read()
    model = safetensors.torch.load(buffer)
```
