### ISSUE TITLE
Serialization in Safetensors implementation

### ISSUE THREAD

**Issue by A2va** [huggingface/safetensors#173]
I think it's a bit weird to use `SafeTensors::deserialize(buffer)` to deserialize but for serialize it's `safetensors::tensor::serialize(data, data_info)`. Maybe the serialization can move in SafeTensors implementation, what do you think ?

**Comment by Narsil** [comment]
Yes the rust API could use some polishing.
 
 The thing is `serialize` has no link to `SafeTensor` so it doesn't make a lot of sense to put it in.
 
 I would maybe create something new which would be `let safetensor: SafeTensor =... ;  safetensor.serialize()`.
Maybe something like that. Do you mind sharing the code you're using ?

Just trying to verify if this works for you, and if APIs could be done differently maybe.

**Comment by A2va** [comment]
Sure! The context is that I'm trying to add safetensors support to tch-rs. 
I have already done the dezerialisation part, and the serialization part is here:
```rust
let mut tensors: BTreeMap<String, TensorView> = BTreeMap::new();
for (name, tensor) in ts.iter() {
	let t = tensor.as_ref();
	
	let shape: Vec<usize> = t.size().iter().map(|&x| x as usize).collect();

	let kind = t.f_kind()?;
	let dtype = Self::kind_to_dtype(kind)?; // Convert tch-rs kind to dtype

	let numel = t.numel();

	let mut content = vec![0u8; numel * kind.elt_size_in_bytes()];
	t.f_copy_data_u8(&mut content, numel)?;

	let view = TensorView::new(dtype, shape, &content);
	tensors.insert(name.as_ref().to_string(), view);
}

safetensors::tensor::serialize_to_file(&tensors, &None, path.as_ref());
```
Also if you don't mind, I need some help but it's not directly related to this issue.
I'm a bit new to Rust rust and it complains over `content` that are not live long enough, which make perfectly sense. 
But how can I handle that ? Because TensorView need reference to data.

**Comment by Narsil** [comment]
Do you have a link to your PR, there's multiple things that could be fixed in this code ;)

The biggest is that you are creating a new vec `content` to get the data, and it's dropped at each step of the loop, since `tensors` need to last outside the loop that's why it's complaining.

You ideally need to get a `&[u8]` from the tensor directly. Not necessarily possible on GPU, but it *is* possible on CPU. In python world, torch gives `data_ptr` (that + n_element and making sure everything is contiguous is enough to get `&[u8]`).

**Comment by A2va** [comment]
My code is [here]

**Comment by Narsil** [comment]
Very nice code already !


I took the liberty of rewriting a bit of it, and adding a bunch of comments everywhere I made modifications or thought it was relevant:

```rust
//! Safetensors support for tensors.
//!
//! Format spec:
//! https://github.com/huggingface/safetensors
use crate::{Device, Kind, TchError, Tensor};

use std::collections::BTreeMap;
use std::path::Path;

use safetensors::tensor;
use safetensors::tensor::{Dtype, SafeTensorError, SafeTensors, TensorView};

impl crate::Tensor {
    // These don't seem to be necessary to be public
    fn dtype_to_kind(dtype: safetensors::tensor::Dtype) -> Result<Kind, TchError> {
        let kind = match dtype {
            Dtype::BOOL => Kind::Bool,
            Dtype::U8 => Kind::Uint8,
            Dtype::I8 => Kind::Int8,
            Dtype::I16 => Kind::Int16,
            Dtype::I32 => Kind::Int,
            Dtype::I64 => Kind::Int64,
            Dtype::BF16 => Kind::BFloat16,
            Dtype::F16 => Kind::Half,
            Dtype::F32 => Kind::Float,
            Dtype::F64 => Kind::Double,
            _ => return Err(TchError::Convert(format!("unsupported dtype in safetensor file"))),
        };
        Ok(kind)
    }

    // These don't seem to be necessary to be public
    fn kind_to_dtype(kind: Kind) -> Result<Dtype, TchError> {
        let dtype = match kind {
            Kind::Bool => Dtype::BOOL,
            Kind::Uint8 => Dtype::U8,
            Kind::Int8 => Dtype::I8,
            Kind::Int16 => Dtype::I16,
            Kind::Int => Dtype::I32,
            Kind::Int64 => Dtype::I64,
            Kind::BFloat16 => Dtype::BF16,
            Kind::Half => Dtype::F16,
            Kind::Float => Dtype::F32,
            Kind::Double => Dtype::F64,
            _ => return Err(TchError::Convert(format!("unsupported kind in safetensor file"))),
        };
        Ok(dtype)
    }

    /// Reads a safetensors file and returns some named tensors.
    pub fn read_safetensors<T: AsRef<Path>>(path: T) -> Result<Vec<(String, Tensor)>, TchError> {
        let file = std::fs::read(&path)?;

        let safetensors = match SafeTensors::deserialize(&file) {
            Ok(value) => value,
            Err(e) => match e {
                SafeTensorError::IoError(e) => return Err(TchError::Io(e)),
                // Always reoutput the error message from the underlying error
                // For easier debugging
                e => {
                    return Err(TchError::FileFormat(format!(
                        "unable to load safetensor file : {e}"
                    )))
                }
            },
        };

        // You can unwrap directly to give better names to your variables
        // for (name, view) in safetensors.tensors() {
        //     let size: Vec<i64> = view.shape().iter().map(|&x| x as i64).collect();

        //     let kind = Self::dtype_to_kind(view.dtype())?;
        //     let tensor = Tensor::f_of_data_size(view.data(), &size, kind)?;
        //     result.push((name, tensor));
        // }

        // Same version, but rustier.
        safetensors
            .tensors()
            .into_iter()
            .map(|(name, view)| -> Result<(String, Tensor), TchError> {
                let size: Vec<i64> = view.shape().iter().map(|&x| x as i64).collect();
                let kind = Self::dtype_to_kind(view.dtype())?;
                let tensor = Tensor::f_of_data_size(view.data(), &size, kind)?;
                Ok((name, tensor))
            })
            .collect()
    }

    /// Writes a tensor in the safetensors format.
    pub fn write_safetensors<P: AsRef<Path>>(
        ts: &[(&str, &Tensor)],
        path: P,
    ) -> Result<(), TchError> {
        let mut tensors: BTreeMap<String, TensorView> = BTreeMap::new();
        for (name, tensor) in ts.iter() {
            if tensor.is_sparse() {
                return Err(TchError::Convert("Cannot save sparse tensors".to_string()));
            }

            // TODO here it would be better to know if tensors `is_contiguous` which
            // doesn't seem available.
            // The problem with force setting this tensor to contiguous is that the tensor
            // will not be the same as the user had before saving after loading.
            // This is better to just refuse saving non contiguous tensors.
            let cpu_tensor = tensor.f_to_device(Device::Cpu)?.f_contiguous()?;
            let shape: Vec<usize> = tensor.size().iter().map(|&x| x as usize).collect();

            let kind = cpu_tensor.f_kind()?;
            let dtype = Self::kind_to_dtype(kind)?;

            let numel = cpu_tensor.numel();
            let size_of_elt = kind.elt_size_in_bytes();

            let length = numel * size_of_elt;
            // Careful, this uses unsafe.
            // In order to make this better Rust API, there needs to be change
            // within `safetensors` rust API. As you could just implement some
            // trait that allows to copy within the file itself.
            /// SAFETY: This is ok, since we're using an owned copy of a Tensor.
            /// We're going to free this unsafe slice right after saving.
            let content: &[u8] =
                unsafe { std::slice::from_raw_parts(cpu_tensor.data_ptr() as *const u8, length) };
            let view = TensorView::new(dtype, shape, content);
            tensors.insert(name.to_string(), view);
        }

        tensor::serialize_to_file(&tensors, &None, path.as_ref())
            .map_err(|e| TchError::Convert(format!("Error while saving safetensor file {e}")))?;

        Ok(())
    }
}
``` 

Now currently this code has to use some `unsafe` + some dubious CPU copy for the entire model (which is not necessary).

This gives me an idea to make a better Rust interface, which could skip a lot of those allocs.
Thanks for sharing !

**Comment by Narsil** [comment]
Also note that I'm a bit saddened that the device is not specified in `read_safetensors`. Now this follow `read_npz` I think, but it should be added imo since there are ways to make this loading much faster there too when you are allocating on GPU.

**Comment by Narsil** [comment]
Hi, 

Thanks for sharing your initial code, it gave me a nice little problem to solve.
I am not sure I found the best iteration yet, but it's good enough to share IMO.

Here is the modified `safetensors`: https://github.com/huggingface/safetensors/pull/179
Here is my take at your PR. https://github.com/Narsil/tch-rs/blob/safetensors/src/tensor/safetensors.rs

You can checkout both my branches to play around:

Essentially to avoid ownership hell, I'm change `.data()` into  `AsRef<[u8]>` which is implemented both by `Vec<u8>` and `&[u8]` . `Vec<u8>` is needed for `tch-rs` on GPU tensors because there's no CPU RAM version of the data which is needed before writing to file.
`&[u8]` Is needed for some tensors which could hold some buffer into a memory mapped file (for instance). 

Now the trait is slightly tricky, but it removes the need for unsafe, the CPU RAM gets deallocated for every tensor while saving from GPU on tch-rs. 

What I don't like is we're copying another copy of each tensors of CPU (but since it's tensor per tensor it might not be that hard, and we could also have 2 different helper structs for CPU vs GPU).

**Comment by A2va** [comment]
> Thanks for sharing your initial code, it gave me a nice little problem to solve.

It is rather my turn to thank you for your help 😄

**Comment by A2va** [comment]
Hi,

I have added `is_contiguous` to tch-rs Tensor and I don't know how handle when the tensor is contiguous. Do I need to return an Error like with a sparse one ? Or we can wrap up around that case differently ?

**Comment by Narsil** [comment]
I'm guessing you mean when the tensor is not contiguous ? 

I would say so to raise an error yes. In practice I found most tensors are contiguous, so it shouldn't be too much of a burden, and it prevents weird things from happening when reloading a tensor (should you make it contiguous on the user's behalf)

**Comment by A2va** [comment]
> I'm guessing you mean when the tensor is not contiguous ?

Yes, it was a bit late when I send the message so, I left some mistakes

**Comment by A2va** [comment]
I have upgraded my branch to the v0.3.0 but I'm facing some issue with the unit tests. 

Sometimes, the safetensors reader returns an order that is different from the previous run. Sometimes it fails at `assert_eq!(named_tensors[0].0, "pi");` because I'm getting 'e' there. Any idea how to work around this?
```rust
fn save_and_load_safetensors() {
    let tmp_file = TmpFile::create("save-and-load-safetensors");
    let pi = Tensor::of_slice(&[3.0, 1.0, 4.0, 1.0, 5.0]);
    let e = Tensor::of_slice(&[2, 7, 1, 8, 2, 8, 1, 8, 2, 8, 4, 6]);
    Tensor::write_safetensors(&[(&"pi", &pi), (&"e", &e)], &tmp_file).unwrap();
    let named_tensors = Tensor::read_safetensors(&tmp_file).unwrap();
    assert_eq!(named_tensors.len(), 2);
    assert_eq!(named_tensors[0].0, "pi");
    assert_eq!(named_tensors[1].0, "e");
    assert_eq!(i64::from(&named_tensors[1].1.sum(tch::Kind::Float)), 57);
}
````

**Comment by Narsil** [comment]
0.3 changed the order of tensors on disk but the order still deterministic (just a different order)

The new order (and extra padding in the header) allows for direct casting of the tensors which mean real zero alloc when using those tensors. Casting requires pointer alignement so by changing order we can guarantee all pointers to be aligned on the same file.

**Comment by A2va** [comment]
Again, thanks for your help ! I will close this issue since the PR is merged in the tch-rs repo.
