### ISSUE TITLE
So how to use this format with stable diffusion pipline? especial the .safetensors of lora

### ISSUE THREAD

**Issue by sunhaha123** [huggingface/safetensors#180]

**Comment by Narsil** [comment]
Do you mean this ?

**Comment by Narsil** [comment]
I created a PR to enable support in `diffusers`. Is that what you meant ?

https://github.com/huggingface/diffusers/pull/2448

**Comment by sunhaha123** [comment]
> I created a PR to enable support in `diffusers`. Is that what you meant ?
> 
> [huggingface/diffusers#2448](https://github.com/huggingface/diffusers/pull/2448)

Absoultely not!  Training lora has at least 4 methods, https://github.com/kohya-ss/sd-scripts; https://github.com/Akegarasu/lora-scripts; webui extention; https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#inference-1.  Thought them are in  format  of safetensors, but they are not same inside!

**Comment by Narsil** [comment]
Well, LoRA are just regular weights, so there's nothing blocking from using `safetensors` for those. 

No offense but both your links are code I have never heard about. I'm happy to help provide guidance in creating `safetensors` lora support in all of them, but I cannot reasonably create all the PRs in all the repos. Just understanding what's going on is going to take me too long.

But basically search of `torch.load/torch.save` and replace with `safetensors.torch.save_file/load_file`  and you should be good.

**Comment by sunhaha123** [comment]
I wish it was. In https://civitai.com/, most of safetensors cant't be load in diffusers.

> Well, LoRA are just regular weights, so there's nothing blocking from using `safetensors` for those.
> 
> No offense but both your links are code I have never heard about. I'm happy to help provide guidance in creating `safetensors` lora support in all of them, but I cannot reasonably create all the PRs in all the repos. Just understanding what's going on is going to take me too long.
> 
> But basically search of `torch.load/torch.save` and replace with `safetensors.torch.save_file/load_file` and you should be good.

I wish it was. In https://civitai.com/, most of safetensors of lora cant't be load in diffusers.

**Comment by sunhaha123** [comment]
> Well, LoRA are just regular weights, so there's nothing blocking from using `safetensors` for those.
> 
> No offense but both your links are code I have never heard about. I'm happy to help provide guidance in creating `safetensors` lora support in all of them, but I cannot reasonably create all the PRs in all the repos. Just understanding what's going on is going to take me too long.
> 
> But basically search of `torch.load/torch.save` and replace with `safetensors.torch.save_file/load_file` and you should be good.

I wish it was. In https://civitai.com/, most of safetensors of lora cant't be loaded in diffusers.

**Comment by sunhaha123** [comment]
https://github.com/huggingface/diffusers/pull/2403

**Comment by khimaros** [comment]
this might be useful while the upstream fix is in progress: https://github.com/huggingface/diffusers/blob/75501a37157da4968291a7929bb8cb374eb57f22/scripts/convert_lora_safetensor_to_diffusers.py

**Comment by williamberman** [comment]
@Narsil's PR adds safetensor's to our current saving and loading of lora weights. Happy to discuss adding more lora/safetensors functionality but we would need more details and would recommend a separate, more detailed issue on diffusers :)

**Comment by Narsil** [comment]
Closing the issue. Feel free to reopen
