### ISSUE TITLE
Rust save ndarray using safetensors

### ISSUE THREAD

**Issue by StrongChris** [huggingface/safetensors#190]
I've been loving this library!

I have a question, how can I save an ndarray using safetensors?

https://docs.rs/ndarray/latest/ndarray/

For context: I am preprocessing data in rust and would like to then load it in python to do machine learning with pytorch.

**Comment by Narsil** [comment]
Something like that:

```rust
use ndarray::{array, Array, Dimension};
use safetensors::tensor::{serialize_to_file, Dtype, View};
use std::borrow::Cow;
use std::path::Path;

struct Wrapper<A, D>(Array<A, D>);

fn main() {
    let a = array![[1., 2., 3.], [4., 5., 6.]];
    let b = array![[1., 2.], [4., 5.]];

    let data = vec![("A", Wrapper(a)), ("B", Wrapper(b))];

    let path = Path::new("model.safetensors");
    serialize_to_file(data, &None, path).unwrap();
}

impl<D: Dimension> Wrapper<f32, D> {
    fn buffer(&self) -> &[u8] {
        let slice = self.0.as_slice().expect("Non contiguous tensors");
        let num_bytes = std::mem::size_of::<f32>();
        let new_slice: &[u8] = unsafe {
            std::slice::from_raw_parts(slice.as_ptr() as *const u8, slice.len() / num_bytes)
        };
        new_slice
    }
}

impl<D: Dimension> View for Wrapper<f32, D> {
    fn dtype(&self) -> Dtype {
        Dtype::F32
    }
    fn shape(&self) -> &[usize] {
        self.0.shape()
    }
    fn data(&self) -> Cow<[u8]> {
        self.buffer().into()
    }
    fn data_len(&self) -> usize {
        self.buffer().len()
    }
}
```

**Comment by StrongChris** [comment]
Thanks! I found that I needed to change `slice.len() / num_bytes` to `slice.len() * num_bytes` to get it to work!

The next issue I am facing is that when I load it in using python (on a different machine), the numbers are wrong. I believe this is due to the endianness of the machines.

The machine I save it from
```python
Python 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as n
>>> import numpy as np
>>> from safetensors.numpy import load_file
>>> t = load_file("model.safetensors")
>>> t
{'A': array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32), 'B': array([[1., 2.],
       [4., 5.]], dtype=float32)}
```

The machine I load it from
```
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from safetensors.numpy import load_file
>>> load_file("rust.safetensors")
{'A': array([[-1.8671875e+00,  2.2864987e-41,  2.2958874e-41],
       [ 2.3048557e-41,  5.9296794e+00, -1.8671875e+00]], dtype=float32), 'B': array([[ 2.3223719e-41,  5.9296794e+00],
       [-1.8671875e+00,  2.2864987e-41]], dtype=float32)}
```

(safetensors versions are identical).

Is this checking of endianess something that should be supported by the library? Or is it something that users should know about and convert for themselves? If so, how can we do the conversion in Rust?

fyi, the same issue happens when working with the python API (I only tested for numpy).

**Comment by Narsil** [comment]
Endianess should always be little endian. 

What kind of machine is your big endian ? (First time I see a real big endian use case).

However a proper check should be in place to prevent saving a big endian tensor: https://github.com/huggingface/safetensors/blob/main/bindings/python/py_src/safetensors/numpy.py#L166

**Comment by Narsil** [comment]
Ohhh you might be loading on a big endian machine. Would that fix it : https://github.com/huggingface/safetensors/pull/193 ?

**Comment by kai-tub** [comment]
Hey, the sample code was quite helpful for me!
Maybe it would be a nice addition to the documentation?
I am fairly new to Rust, so maybe it is trivial for others.
I think given the nice features of `safetensors`, quite a few might benefit from this example to serialize data into a 'cross-language' tensor format. :)
