### ISSUE TITLE
Provide a function to load metadata

### ISSUE THREAD

**Issue by thomasw21** [huggingface/safetensors#194]
Right now the `load` function allows to load the data within a `safetensors` file and outputs a `Dict[str, torch.Tensor]`. However there's no way to load the metadata (unless one uses `safe_open`):
 - `load` definition: https://github.com/huggingface/safetensors/blob/454924be76cb1c3c8c270dd775fc4c8280ae3ebd/bindings/python/py_src/safetensors/torch.py#L105

Same goes for `load_file`

Options are:
 - change the output of `load` in order to support this new usecase
 - provide another function for this use specifically.

**Comment by thomasw21** [comment]
Well effectively the return type can only be `Dict[str, str]` since that's the only format supported for saving.

**Comment by jnordberg** [comment]
👍 This is sorely needed

**Comment by jnordberg** [comment]
In addition to providing a function I suggest adding a `"__st_metadata__"` key to objects returned by load functions since reading and parsing the metadata twice isn't ideal

**Comment by schoenid** [comment]
still required by some users ...
