### ISSUE TITLE
safe_open fails on mergerfs mount

### ISSUE THREAD

**Issue by M1kep** [huggingface/safetensors#195]
Whenever I attempt to load a safetensors file from a [mergerfs](https://github.com/trapexit/mergerfs) mount, the below error is triggered. The safetensors file is successfully created, but safe_open is unable to load it.

```
Traceback (most recent call last):
    File "/tmp/test_safe_tensors/main.py", line 12, in <module>
        with safe_open(f"{path}model.safetensors", framework="pt", device="cpu") as f:
OSError: No such device (os error 19)
```

I'm using a slightly modified version of the example in the README:
```python
from safetensors import safe_open
from safetensors.torch import save_file
import torch

tensors = {
   "weight1": torch.zeros((1024, 1024)),
   "weight2": torch.zeros((1024, 1024))
}

path = "./mergepoint/"

save_file(tensors, f"{path}model.safetensors")

tensors = {}
with safe_open(f"{path}model.safetensors", framework="pt", device="cpu") as f:
   for key in f.keys():
       tensors[key] = f.get_tensor(key)
```

**Comment by M1kep** [comment]
Of course I find the solution right after giving up and creating an issue 😅

It looks like safetensors uses `mmap` which requires a specific set of flags on the mergerfs mount. At the time of writing they are:
`allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=mfs`

For anybody in the future, be sure to search the [mergerfs](https://github.com/trapexit/mergerfs) README for `mmap`

**Comment by Narsil** [comment]
Thanks for giving the solution here !

**Comment by yuange555** [comment]
> ```python
> safe_open
> ```

how to use this settings on safetensors code

**Comment by Narsil** [comment]
https://huggingface.co/docs/safetensors/index#load-tensors

This should contain your answer !

**Comment by jiahuanluo** [comment]
How to fix this on transformers code?

**Comment by arrowonstr** [comment]
the same issue
```
[rank0]:   File "/root/autodl-tmp/project/flux-d/x-flux/train_flux_lora_deepspeed.py", line 51, in get_models
[rank0]:     model = load_flow_model2(name, device="cpu")
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/autodl-tmp/project/flux-d/x-flux/src/flux/util.py", line 276, in load_flow_model2
[rank0]:     sd = load_sft(ckpt_path, device=str(device))
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/miniconda3/envs/flux-dev/lib/python3.11/site-packages/safetensors/torch.py", line 308, in load_file
[rank0]:     with safe_open(filename, framework="pt", device=device) as f:
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: OSError: No such device (os error 19)
```
