### ISSUE TITLE
Prebuilt conda package for m1/apple silicon

### ISSUE THREAD

**Issue by user799595** [huggingface/safetensors#199]
Following up on issue: https://github.com/huggingface/safetensors/issues/153.

It would be nice if there was a pre-built conda package for Apple Silicon, as has been done for pip.

(I'm sorry, I don't know enough about dev ops to help with a PR)

**Comment by Narsil** [comment]
Sorry but this is quite low priority for me at the moment I think.

M1 releases are run on a custom runner and are already some work to keep up.
Conda by itself is quite non trivial to manage so I don't think adding it is really worth it. 

Definitely on the todo list once m1 hit default GH runner.
