### ISSUE TITLE
`safetensor.torch.save_file()` throws `RuntimeError` - any recommended way to enforce?

### ISSUE THREAD

**Issue by drahnreb** [huggingface/safetensors#202]
was confronted with `RuntimeError: Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again`.
Can we explicitly disregard "**potential** differences"?

**Comment by Narsil** [comment]
>  Can we explicitly disregard "potential differences"?

No, this is a serious issue regarding the file, and it's always better to confront it upfront rather than save erroneous files.

> Some tensors share memory,

This means that you have two tensors using the same buffer:

```python
A = torch.zeros((10, 10))
B = A[:2]
```

A & B now share the same buffer, and B is really indexing into A, which means modifications in A will modify B and vice versa.

Now this is a problem for saving on disk since after reload you won't have that property depending on how you load them and if you load them on different devices for instance.

As a result, shared tensors are not allowed on disk, if you want that property, you would need to save only A, and recreate B after reload (it's essentially free since A will be already loaded). This is how it's done within `transformers` for sharing the token embeddings and the last LM layer (which are the same tensors)

It really depends on what those shared tensors do, they sometimes are actually just duplicates and you can just save one of them. More complicated situation could exist where 3 tensors refer to each other, in non-overlapping ways.

For reference, we recently had troubles with some llama weights being 37Gb instead of 26Gb and it was linked to something like saving B on disk, but torch by default will save the entire A buffer, not just the B view leading to massively larger file than necessary (and no way to access A again from this file)

Does this information help ?

If you're willing to share a bit more details about those tensors, I would be happy to help thinking of solutions

**Comment by patrickvonplaten** [comment]
@Narsil I'm also getting this error for a relatively simple task:

```py
from transformers import T5EncoderModel

model = T5EncoderModel.from_pretrained("t5-small")
model.save_pretrained("./temp", safe_serialization=True)
```

**Comment by Narsil** [comment]
It's definitely an issue in transformers.

Proposed fix: 

https://github.com/huggingface/transformers/pull/22437

**Comment by drahnreb** [comment]
@Narsil Thanks for the detailed answer and the reference to the PR.

I'm aware of the concept of how tensors can share memory in different ways.

Like @sgugger said it should be up to the user to decide with 
> flexibility
e.g to save redundantly (if exact duplicates).

In line with @sgugger:
> In Transformers when you save and reload weights as Transformers, we always takes care of re-tying the weights and yes they may be saved twice if the proper variables are not set, but that doesn't mean the workflow of saving and reloading does not work.

Also, instead of an absolute solution, could we save meta information about such buffer structure to recover during load and enable a generic save and reloading workflow?

**Comment by mar-muel** [comment]
Hi all - I'm facing this error when saving a transformers model inside a thread pool.

My code looks roughly like this
```python
from safetensors.torch import save_file

def convert(vae, unet, text_encoder):
    # This method is run by a thread

    # convert models here...
    state_dict = {**unet.state_dict(), **vae.state_dict(), **text_encoder.state_dict()}
    
    # trying to apply the solution described above
    state_dict = {k: v.clone().contiguous() for k, v in state_dict.items()}
    
    # save as safetensors
    save_file(state_dict, out_dir)
```
Interestingly, the issue only occurs for the `text_encoder` which is of type `CLIPTextModel`. The diffusers models (unet and vae) don't complain.

@Narsil Do you have suggestions how to fix? I've tried to create a deep-copy of the weights before shipping it off to the thread, but no luck... 

I'm using `safetensors==0.3.0` and `transformers==4.28.1`.

This is the full trace:

```text
line 292, in convert
    save_file(state_dict, out_dir)
  File "/usr/local/lib/python3.8/site-packages/safetensors/torch.py", line 72, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/usr/local/lib/python3.8/site-packages/safetensors/torch.py", line 233, in _flatten
    raise RuntimeError(
RuntimeError: Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.0.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.layer_norm2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.7.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.out_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.6.mlp.fc2.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.out_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.2.mlp.fc2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.5.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.7.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.5.layer_norm2.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.self_attn.v_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.3.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.8.self_attn.q_proj.weight', 'cond_stage_model.transformer.text_model.embeddings.token_embedding.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc1.weight', 'cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.embeddings.position_embedding.weight', 'cond_stage_model.transformer.text_model.encoder.layers.1.mlp.fc1.bias', 'cond_stage_model.transformer.text_model.encoder.layers.6.self_attn.k_proj.bias', 'cond_stage_model.transformer.text_model.encoder.layers.1.self_attn.v_proj.weight', 'cond_stage_model.transformer.text_model.encoder.layers.4.self_attn.out_proj.weight'}]
```

**Comment by Narsil** [comment]
Hey,

This error is not linked to threading, but more to this https://github.com/huggingface/safetensors/pull/236

 Basically some tensors are sharing a buffer, which is not allowed on disk (reasons detailed on the PR).
 Hopefully the PR could help make sound decisions for you. It cannot cover all cases since there are definitely some edge cases there,  but it you be good.
 
 Also in `transformers` you can do `model.save_pretrained(..., safe_serialization=True)`  which should also take care of those issues for you.

**Comment by johnchienbronci** [comment]
I'm also getting this error:

from safetensors.torch import save_file as safe_save_file

adapter_file = WAV2VEC2_ADAPTER_SAFE_FILE.format(data_args.target_language)
adapter_file = os.path.join(training_args.output_dir, adapter_file)
logger.info(f"Saving adapter weights under {adapter_file}...")
safe_save_file(model._get_adapters(), adapter_file, metadata={"format": "pt"})

```
RuntimeError:                                                                                                                                      
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again:               
[{'wav2vec2.encoder.layers.3.adapter_layer.linear_1.weight', 'wav2vec2.encoder.layers.45.adapter_layer.linear_2.bias',                             
'wav2vec2.encoder.layers.0.adapter_layer.norm.bias', 'wav2vec2.encoder.layers.10.adapter_layer.linear_1.weight',                                   
'wav2vec2.encoder.layers.33.adapter_layer.norm.bias', 'wav2vec2.encoder.layers.41.adapter_layer.norm.weight',                     
```

============ 
I'm reference `https://huggingface.co/docs/safetensors/torch_shared_tensors`, save_file instead to save_model

from safetensors.torch import `save_model` as safe_save_file
adapter_file = WAV2VEC2_ADAPTER_SAFE_FILE.format(data_args.target_language)
adapter_file = os.path.join(training_args.output_dir, adapter_file)
logger.info(f"Saving adapter weights under {adapter_file}...")
safe_save_file(model, adapter_file, metadata={"format": "pt"})

```
RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'wav2vec2.encoder.layers.18.adapter_layer.norm.bias', 'wav2vec2.encoder.layers.30.adapter_layer.norm.bias', 
'wav2vec2.encoder.layers.2.adapter_layer.linear_2.weight', 'wav2vec2.encoder.layers.3.adapter_layer.linear_1.weight', 
'wav2vec2.encoder.layers.16.adapter_layer.norm.bias', 'wav2vec2.encoder.layers.36.adapter_layer.linear_1.bias', 
'wav2vec2.encoder.layers.6.adapter_layer.linear_2.bias', 'wav2vec2.encoder.layers.34.adapter_layer.norm.weight', 
'wav2vec2.encoder.layers.42.adapter_layer.linear_1.weight', 'wav2vec2.encoder.layers.1.adapter_layer.linear_1.bias', 
'wav2vec2.encoder.layers.5.adapter_layer.linear_1.bias', 'wav2vec2.encoder.layers.5.adapter_layer.linear_2.bias', 
'wav2vec2.encoder.layers.19.adapter_layer.linear_1.bias', 'wav2vec2.encoder.layers.19.adapter_layer.linear_2.bias', 
'wav2vec2.encoder.layers.30.adapter_layer.linear_2.weight', 'wav2vec2.encoder.layers.37.adapter_layer.linear_2.bias', 
'wav2vec2.encoder.layers.45.adapter_layer.norm.weight', 'wav2vec2.encoder.layers.31.adapter_l
....
}
```
@Narsil  Do you have suggestions how to fix?

**Comment by Narsil** [comment]
How can I reproduce this ?

> Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst

This means that all tensors are shared, but None actually own the entire storage buffer, so there's no way to store this in `safetensors` and make it nicely reloadable. We need to find a correct tensor that will keep everything.

However I'm unaware of a lib that would behave like that. https://github.com/huggingface/transformers/blob/61d3928bfb3029bceb5be3e68ca3d4bf8456758f/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L984-L1012 Nothing seems to suggest that the weights should be shared.

Could it be that none of these are actually allocated and all on on `device("meta")` ? This could behave that way.

**Comment by johnchienbronci** [comment]
The error occurred when I executed this script. [run_speech_recognition_ctc_adapter.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/speech-recognition/run_speech_recognition_ctc_adapter.py)
```
python run_speech_recognition_ctc_adapter.py \
	--dataset_name="common_voice" \
	--model_name_or_path="facebook/mms-1b-all" \
	--dataset_config_name="zh-TW" \
	--output_dir="./wav2vec2-common_voice-tr-mms-demo" \
	--num_train_epochs="4" \
	--per_device_train_batch_size="32" \
	--learning_rate="1e-3" \
	--warmup_steps="100" \
	--evaluation_strategy="steps" \
	--text_column_name="sentence" \
	--length_column_name="input_length" \
	--save_steps="200" \
	--eval_steps="100" \
	--save_total_limit="3" \
         --target_language="zh-TW" \
	--gradient_checkpointing \
	--chars_to_ignore , ? . ! - \; \: \" “ % ‘ ” � \
	--fp16 \
	--group_by_length \
	--do_train --do_eval
```

**Comment by Narsil** [comment]
I just tried with --model_name_or_path="facebook/mms-300m"  (local GPUcouldn't find the larger one).

And everything worked fine.
And I tried with just meta weights and the error is different.. odd..

**Comment by johnchienbronci** [comment]
I encounter a CUDA out of memory issue regardless of whether I use "facebook/mms-1b-all" or "facebook/mms-300m" models. However, I have resolved this issue by using DeepSpeed. 


Does the message `Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again` have any connection to DeepSpeed?

deepspeed config: 
```
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
   "scheduler": {
         "type": "WarmupDecayLR",
         "params": {
             "last_batch_iteration": -1,
             "total_num_steps": "auto",
             "warmup_min_lr": "auto",
             "warmup_max_lr": "auto",
             "warmup_num_steps": "auto"
         }
     },
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto"
}
```

**Comment by Narsil** [comment]
> ave any connection to DeepSpeed?

Possibly, I have no idea how deepspeed works.
Since I cannot reproduce here is how I would go about it.

- Place a debugger (`ipdb.set_trace()` for instance) right before saving.
- Get to the debugger and look at the faulty tensors:
   `'wav2vec2.encoder.layers.2.adapter_layer.linear_2.weight'` What is the shape ? What is the device ?
   `tensor = state_dict[name];` and then show `tensor.untyped_storage().data_ptr()`. Do that for several layers.
   Give as much info as you can for a few of those tensors. We're looking for similarities and differences.
   
My guess is that deepspeed prevents OOM by actually not allocating the data (meaning those `data_ptr()` will probably yield 0 and be null pointers, and use some mecanism to put back memory sometime later.)

That or deepspeed messes around with the tensor storages, in any case it's lacking a step before you can save your tensors.
You could also try saving using `torch.save` to see if that work better (after reloading too)

**Comment by johnchienbronci** [comment]
I resolved the CUDA out of memory issue by modifying the compute_metrics() and preprocess_logits_for_metrics() functions. 
Now, I can successfully execute the script without using DeepSpeed.
```
  trainer = Trainer(
      compute_metrics=compute_metrics,
      preprocess_logits_for_metrics=preprocess_logits_for_metrics,
      ....
  )
  def compute_metrics(pred):
      labels_ids = pred.label_ids
      pred_ids = pred.predictions[0]

      preds = np.where(pred_ids != -100, pred_ids, tokenizer.pad_token_id)
      pred_str = tokenizer.batch_decode(preds, skip_special_tokens=True)
      labels_ids[labels_ids == -100] = tokenizer.pad_token_id
      label_str = tokenizer.batch_decode(labels_ids, skip_special_tokens=True)
      metrics = {k: v.compute(predictions=pred_str, references=label_str) for k, v in eval_metrics.items()}
      return metrics

  def preprocess_logits_for_metrics(logits, labels):
      """
      Original Trainer may have a memory leak. 
      This is a workaround to avoid storing too many tensors that are not needed.
      """
      pred_ids = torch.argmax(logits, dim=-1)
      return pred_ids, labels
```

**Comment by BramVanroy** [comment]
Just for future sake: I also get the mentioned RuntimeError (Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again:) when using deepspeed. For now I will not use safetensors during training and do the conversion after training instead.

**Comment by mar-muel** [comment]
@BramVanroy I'd be curious whether you could avoid this issue by loading the model in a threading lock (as described in my comment above).

**Comment by BramVanroy** [comment]
@mar-muel Yhamks for the tip, I might try later. Curious to know why this is happening though.

**Comment by Narsil** [comment]
@BramVanroy any trivial script on smallish model we could run to reproduce ? I would like to get a better understanding of what deepspeed is doing and if maybe there was a way to making saving in safetensors easy.

**Comment by BramVanroy** [comment]
> @BramVanroy any trivial script on smallish model we could run to reproduce ? I would like to get a better understanding of what deepspeed is doing and if maybe there was a way to making saving in safetensors easy.

I currently do not have the time to write a test case but maybe you can modify one of the deepspeed tests in `transformers`? https://github.com/huggingface/transformers/tree/main/tests/deepspeed

**Comment by strint** [comment]
> > Like @sgugger said it should be up to the user to decide with
> 
> We can add a function like
> 
> `weights = remove_duplicate(weights)` `weights = {k: v.contiguous() for k, v in weighs.items()`
> 
> There's a lot of way to deal with those shared buffers, and there's not just 1 obvious solution which is why such thing is not already done.
> 
> You can have 2 shared buffers, which don't share data:
> 
> ```python
> A = torch.zeros((10, 10))
> B = A[::2, :]
> C = A[1::2, :]
> save_file({"B": B, "C": C}, filename)
> ```

The same problem occurs to me while trying to convert  PyTorch state_dict tensors to safetensors. Error message:


> RuntimeError: Error while trying to find names to remove to save state dict, but found no suitable name to keep for saving amongst: {'model.layers.22.mlp.gate_proj.weight', 'model.layers.22.mlp.up_proj.weight'}. None is covering the entire storage.Refusing to save/load the model since you could be storing much more memory than needed. Please refer to https://huggingface.co/docs/safetensors/torch_shared_tensors for more information. Or open an issue.


It turns out that `model.layers.22.mlp.gate_proj.weight` and `model.layers.22.mlp.up_proj.weight` are both a slice of the same tensor.

Tensor slice in PyTorch is a view operation which means that they shared the same memory storage. When we only save the sliced tensors without the original not sliced tensor.  `_remove_duplicate_names` in safetensors will raise the error above. The error complains that it can find the not sliced tensor( I have not understood why safetensors need the not sliced tensor).

A quick way to fix this is use `tensor.clone()` to process the shared tensor in original state_dict, which will disable the memory shared between view tensors.

**Comment by Narsil** [comment]
> A quick way to fix this is use tensor.clone() to process the shared tensor in original state_dict, which will disable the memory shared between view tensors.

It works here because there's no real reason for the sharing (afaik the weights are actually disjoint). But it's really hard to infer that from this library, and even then there might be good reasons why the sharing was done.

**Comment by SefaZeng** [comment]
So what is the best way to solve this issue? If I set tie_word_embedding to True for one model, the `lm_head.weight` and `word_embedding.weight` will share the same buffers, and when I try to convert to tensor-rt file it raises this error.

**Comment by SefaZeng** [comment]
> So what is the best way to solve this issue? If I set tie_word_embedding to True for one model, the `lm_head.weight` and `word_embedding.weight` will share the same buffers, and when I try to convert to tensor-rt file it raises this error.

And if I use `tensor.clone()` to make sure the `lm_head.weight` and `word_embedding.weight` use different buffers, it will consume double the memory of the GPU, right? As I understand, they share the same memory in a pure torch script.
