### ISSUE TITLE
Use cargo.lock to make the project reproducible

### ISSUE THREAD

**Issue by MatthewCroughan** [huggingface/safetensors#229]
Building the project at two different times of day may produce very different results, because the project is not storing a lock file, and it is in the `.gitignore`. It would be helpful for projects like my own which attempt to make incredibly complex generative AI software more reproducible (https://nixified.ai) if you did this.

**Comment by Narsil** [comment]
It is both.

We could freeze the `Cargo.lock` for the python package. Would that be enough ?

**Comment by max-privatevoid** [comment]
That will be enough to serve our purpose. Will this lockfile be kept up-to-date as the project evolves?

**Comment by Narsil** [comment]
Yes. 

If it becomes annoying (Because of constant modifications to it) we could keep it only for the released branches, which I think would be enough.
