### ISSUE TITLE
C Bindings

### ISSUE THREAD

**Issue by SomeoneSerge** [huggingface/safetensors#237]
This is a tracking issue.

TLDR: I think it would be important for many things to maintain C bindings, cf. https://github.com/huggingface/safetensors/issues/222#issuecomment-1509988573 and I'll fill in the proper issue description later. Thanks

**Comment by mfuntowicz** [comment]
Hi @SomeoneSerge 

I've been implementing a C-API binding for safetensors lately.

If you want to give it a try, happy to help.

-> https://github.com/huggingface/safetensors/pull/259
