### ISSUE TITLE
Small Typo in Rust Docs

### ISSUE THREAD

**Issue by mert-kurttutan** [huggingface/safetensors#250]
See here which should explain the names() method: https://github.com/huggingface/safetensors/blob/main/safetensors/src/tensor.rs#L377

But the docs instead repeats the explanation for `tensor method`.

If you want,, I can provid quick PR.

**Comment by Narsil** [comment]
That would be lovely !

**Comment by dirac3000** [comment]
You can pick my PR if it helps!
