### ISSUE TITLE
ONNX has just become twice as fast as before. Can SafeTensors also achieve that?

### ISSUE THREAD

**Issue by WEBPerformace** [huggingface/safetensors#258]
Here are some announcements and technical details. It's nice to see that they are making significant improvements. Could some of that be useful and implemented for SafeTensors?

https://devblogs.microsoft.com/directx/dml-stable-diffusion/
https://www.tomshardware.com/news/nvidia-geforce-driver-promises-doubled-stable-diffusion-performance
https://build.microsoft.com/en-US/sessions/47fe414f-97b8-4b71-ae9e-be9602713667

![image](https://github.com/huggingface/safetensors/assets/121736447/6c4b83ad-416f-4809-99f1-dd6481292cbc)

**Comment by chris-ha458** [comment]
Safetensors describe a `format for storing tensors safely (as opposed to pickle) and that is still fast (zero-copy).`

Usually it is not the rate limiting step for model training or inference.
Storage, sharing and deployment of models, however suffered from a lack of safe and fast standard and this is what this repository is about.

**Comment by Narsil** [comment]
This performance improvement seems related to inference, and not storage.

Load performance is one aspect of this repo, and I think it's pretty hard to beat (since it's zero-copy with lazy loading).

Closing. Feel free to reopen if our answers weren't clear.
