### ISSUE TITLE
Issue with Loading Model in safetensors Format

### ISSUE THREAD

**Issue by yachty66** [huggingface/safetensors#273]
### System Info

- `transformers` version: 4.30.1
- Platform: macOS-13.4-arm64-arm-64bit
- Python version: 3.11.3
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

I'm trying to load a model saved in safetensors format using the Transformers library. Here's the code I'm using:

```python
from transformers import LlamaForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained("path/to/model")
model = LlamaForCausalLM.from_pretrained("path/to/model", use_safetensors=True)
```

However, I'm running into this error:

```
Traceback (most recent call last):
  File "/Users/maxhager/Projects2023/nsfw/model_run.py", line 4, in <module>
    model = LlamaForCausalLM.from_pretrained("path/to/model", use_safetensors=True)
  File "/Users/maxhager/.virtualenvs/nsfw/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory path/to/model.
```

In my model directory, I have the following files (its [this](https://huggingface.co/notstoic/pygmalion-13b-4bit-128g) model locally):

- 4bit-128g.safetensors
- config.json
- generation_config.json
- pytorch_model.bin.index.json
- special_tokens_map.json
- tokenizer.json
- tokenizer.model
- tokenizer_config.json

### Expected behavior

I would expect that setting use_safetensors=True would inform the from_pretrained method to load the model from the safetensors format. However, it appears the method is looking for the usual model file formats (pytorch_model.bin, tf_model.h5, etc) instead of recognizing the safetensors format.

I'm looking for a solution or guidance on how to successfully load a model stored in the safetensors format using the Transformers library.

**Comment by Narsil** [comment]
Hey. 

The directory is missing `model.safetensors` which is required to load the model (error isn't super clean on that).
Have you saved in safetensors first ?  `save_pretrained(..., safe_serialization=True)`

Reloading `from_pretrained(...); save_pretrained(...safe_serialization=True); from_pretrained(...., use_safetensors=True)` should yield the desired results.

You have however the 4bit quantized model (I'm guessing GPTQ), which you might be able to use but not with `from_pretrained`.

**Comment by yachty66** [comment]
@Narsil hey! i am using [this](https://huggingface.co/notstoic/pygmalion-13b-4bit-128g) model. its in safetensors format already. you are saying 4bit quantized models cannot be used with HF transformers?

**Comment by Narsil** [comment]
Not directly no, `transformers` hasn't support for GPTQ. 

There are multiple things you can do, which the author of this model probably has done.

- Reloading from_pretrained(...); save_pretrained(...safe_serialization=True); from_pretrained(...., use_safetensors=True) should yield the desired results.
- You can convert it https://huggingface.co/spaces/safetensors/convert and use your PR as a base (so you don't have to open this author's pickled file).

Once this is done your code will work, but still not use the quantized version, for that you probably will need https://github.com/qwopqwop200/GPTQ-for-LLaMa with `make_quant_linear` and another round of loading the weights from the quantized model.

Either that or create an empty model, `make_quant_linear`, and *then* load from the `4b` model file. Nothing too hard if you know what you're doing, but definitely not as easy as `from_pretrained(..)`.

**Comment by yachty66** [comment]
@Narsil the model is already in safetensors format, see [here](https://huggingface.co/notstoic/pygmalion-13b-4bit-128g/blob/main/4bit-128g.safetensors). I.e. loading the model in the first step with from_pretrained(...) is not possible because i am getting this error:

```
Traceback (most recent call last):
  File "/Users/maxhager/Projects2023/nsfw/model_run.py", line 4, in <module>
    model = LlamaForCausalLM.from_pretrained("path/to/model", use_safetensors=True)
  File "/Users/maxhager/.virtualenvs/nsfw/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory path/to/model.
```

**Comment by Narsil** [comment]
This file is NOT what `transformers` expect.

It will not even attempt to read it, and it wouldn't work if you simply renamed it, because it doesn't contain what it's supposed to for `transformers` to work.
Safetensors is a container format, but if the tensors on the file do not correspond to what the code expect, it will not work.

You could try this: 
```
CUDA_VISIBLE_DEVICES=0 python llama_inference.py ${MODEL_DIR} --wbits 4 --groupsize 128 --load llama7b-4bit-128g.safetensors --text "this is llama" --device=0
```

Taken from https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by yachty66** [comment]
@Narsil I ended up using [AutoGPTQ](https://github.com/PanQiWei/AutoGPTQ) for quantization and inference, but something is still off. The output when performing inference doesn't make sense, as seen in [this Colab](https://colab.research.google.com/drive/1P2tanfjflTYj-FOUP9D9AIzYlhxrtz8j).

**Comment by Narsil** [comment]
This doesn't seem to be linked to `safetensors` in anyway. 

Maybe the quantized version is just bad. Have you checked the errors of your tensors during quantization ? 
Also the prompting is really important, you may not have used the same prompting during the sampling for the quantization (or after).

You can also reduce the size of the group,  see if that helps. But quantization doesn't work equally well on all models.

**Comment by dtorber** [comment]
I am having more or less the same problem with my code, because I am trying to load an  AutoModelForSeq2SeqLM that I have trained and saved in safetensors format but now I can't get it loaded, because using 
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint) gives me OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory path/to/model.

And if I activate use_safetensors=true then I get that the model does not have a JSON valid format, so I don't know how to load this model in safetensors format

Thank you

**Comment by Narsil** [comment]
Which transformers version are you using ?

Could you share your actual weight file ?

> I get that the model does not have a JSON valid format,

Seems to hint the safetensors file is corrupted somehow.
Could we reproduce somehow ?

**Comment by RomuloNextly** [comment]
I solved the issue by upgrading transformers.

pip install -U transformers.
