### ISSUE TITLE
InvalidHeaderDeserialization error if __metadata__ in header contain numbers

### ISSUE THREAD

**Issue by by321** [huggingface/safetensors#278]
### System Info

Hi,

I'm having an issue with one of my safetensors files, eventually, it seems safe_open() would fail if __metadata__ contains an integer value. In the attached zip file, there're two .safetensors files, the only difference is in __metadata__ in header.

In 0.safetensors:

`"__metadata__": {"quoted_int":"0"}`

In 1.safetensors:

`"__metadata__": {"unquoted_int":0}`

safe_open() can open 0.safetensors, but not 1.safetensors. Here's my test script:

```
import torch
from safetensors import safe_open

with safe_open( "0.safetensors", framework="pt", device="cpu") as f0:
    print("0 opened")

with safe_open( "1.safetensors", framework="pt", device="cpu") as f1:
    print("1 opened")
```

This is the output:

```
0 opened
Traceback (most recent call last):
  File "c:\code\python\test\test_st.py", line 7, in <module>
    with safe_open( r"d:\1.safetensors", framework="pt", device="cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization
```
[test_st.zip](https://github.com/huggingface/safetensors/files/11830720/test_st.zip)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

1. Extract attached zip file into a directory.
2. Run "python test_st.py".

Python output:

0 opened
Traceback (most recent call last):
  File "D:\tmp\test_st.py", line 7, in <module>
    with safe_open( "1.safetensors", framework="pt", device="cpu") as f1:
safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

### Expected behavior

Python output:

0 opened
1 opened

**Comment by Narsil** [comment]
Yes this is normal:

https://github.com/huggingface/safetensors#format

> A special key __metadata__ is allowed to contain free form text-to-text map.

Arbitrary JSON is not allowed, so numbers are not.

**Comment by by321** [comment]
OK, got it. In this case, I suggest putting a more explicit note about this restriction to make it more obvious:

`A special key "__metadata__" is allowed to contain free form text-to-text map. Only string values are supported in metadata, arbitrary JSON is not allowed.`

**Comment by julien-c** [comment]
good idea IMO

**Comment by Narsil** [comment]
Sure do you want to open a PR ?

**Comment by by321** [comment]
PR submitted.

**Comment by Niuwujia** [comment]
Hi,
how could you get "__metadata__" of safetensors while you can't open it?
I meet the same error, but I can't verify if the reason is the same with yours.

**Comment by by321** [comment]
> Hi, how could you get "**metadata**" of safetensors while you can't open it? I meet the same error, but I can't verify if the reason is the same with yours.

I have a small utility that let you extract metadata or entire header :  https://github.com/by321/safetensors_util
Once extracted, it's just a json file, so you can open it with a text editor.

Unless the first 8 bytes of the file are corrupted, then you need to open it in a binary viewer/editor.
