### ISSUE TITLE
Support the "meta" device on load_file()

### ISSUE THREAD

**Issue by lstein** [huggingface/safetensors#281]
### Feature request

Support the following syntax for obtaining an object containing the tensor shapes and other metadata without loading the actual tensors:

```
model = safetensors.torch.load_file(path, device="meta")
```

### Motivation

This would be analogous to `torch.load(path, map_location="meta")` and allows the metadata to be interrogated without having to load the whole safetensors into memory.

### Your contribution

Happy to test the implementation.

**Comment by Narsil** [comment]
Have you tried the following ?
```python
with safe_open(filename, framework="pt") as f:
     print(f.keys())
     print(f.get_slice("mytensor").shape)
     print(f.metadata())
```

Should be pretty instant and it doesn't allocate anything

**Comment by keturn** [comment]
Is there a way to get data types from that? I don't see it exposed on PySafeSlice.

**Comment by Narsil** [comment]
Indeed it seems to be missing.

**Comment by Edenzzzz** [comment]
This doesn't work in safetensors 0.5.3 

![Image](https://github.com/user-attachments/assets/6e8ac4ba-53e7-4120-bbdc-2e645c5e5b51)

**Comment by Edenzzzz** [comment]
Oh I see it's `f.get_slice(name).get_shape()`
