### ISSUE TITLE
Converting bin to safetensors as part of loading a local model with text-generation-inference is not producing the whole set of safetensors

### ISSUE THREAD

**Issue by hlo-world** [huggingface/safetensors#295]
### System Info

Docker running tgi 9.0 on ECS EC2 with g5 instances

### Reproduction

I am setting up tgi on ECS, and am trying to load falcon-40b from a local EFS data/falcon-40b/

On a particular run, because I did not have the safetensors yet, it began converting bin to safetensors:

`No safetensors weights found for model /data/falcon-40b at revision None. Converting PyTorch weights to safetensors.`

However, on a subsequent run, I notice that it is complaining about missing weights

`RuntimeError: weight transformer.word_embeddings.weight does not exist`

I checked the content of EFS, and notice that it only has parts of the models converted to safetensors:

`model-00003-of-00009.safetensors`
`model-00007-of-00009.safetensors`

Also, I see that HF staff members opening PRs as a result of converting to safetensor using https://huggingface.co/spaces/safetensors/convert also end up with PRs that contain incomplete set of safetensors:

https://huggingface.co/tiiuae/falcon-40b/discussions/78
https://huggingface.co/tiiuae/falcon-40b/discussions/79

### Expected behavior

Seems to be a bug, I am expecting 9 pieces of safetensors for this model that started with 9 pieces of bin.

**Comment by hlo-world** [comment]
Was able to get all the safetensor parts after wiping the EFS and starting over. I noticed that my Shard number had to be equal to number of GPUs (8 on a 48xlarge) for the safetensor conversion to not fail part way through.

Still curious about the PRs with incomplete set of safetensors.

**Comment by stas00** [comment]
Honestly I had no idea those PRs were opened, as the conversion space failed and gave no indication of what happened or what was created.

I have closed:
https://huggingface.co/tiiuae/falcon-40b/discussions/78
https://huggingface.co/tiiuae/falcon-40b/discussions/79
