### ISSUE TITLE
Meta tensors should not be recognized as duplicates

### ISSUE THREAD

**Issue by shingjan** [huggingface/safetensors#300]
### System Info

safetensor version 0.3.1

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

If you create a nn module and load this module with meta tensors as `weight` and `bias`, safetensors will complain that one of the`weight` and `bias` tensors should be removed due to duplication. The reason is the storage ptr of meta tensors are all fallen back as 0. I wonder if it is possible that we can come up with a way to uniquely identify meta tensors instead of the `(storage_ptr, device)` tuple. 

### Expected behavior

Meta tensors shouldn't be recognized as duplicates.

**Comment by Narsil** [comment]
Well, we cannot save meta tensors either (since they are not holding the data either).

If you can share what you're doing, we can try to improve the error message, but I'm not sure how we can save anything if there's no data in your tensors.

**Comment by shingjan** [comment]
@Narsil thanks for the reply! My use case is that during loading tensors in safetensors format, those loaded tensors got converted to meta tensors and some nn modules will load those meta tensors as parameters. But in the `save_model` api, there is a check about if tensors share the same storage, for de-duplication purposes I guess. And any meta tensor will fail that check as they have the same data ptr. I wonder if that makes sense to support meta tensors in safetensors or probably come up with a way to distinguish meta tensors in some other ways?

**Comment by Narsil** [comment]
We **cannot** save data from meta tensors.

You are expliciting asking us to save them, but we just cannot (becuase they don't hold data).

You need to fix your script (by filtering out meta tensors if you don't need them) or figuring out how to populate them.

**Comment by Narsil** [comment]
Closing, feel free to reply if you can provide further information to understand the issue.
