### ISSUE TITLE
Stable Diffusion loading times are slow and then the same

### ISSUE THREAD

**Issue by aviadmx** [huggingface/safetensors#301]
### System Info

Ubuntu 18
Python 3.10.11
safetensors 0.3.1
diffusers 0.15.1
transformers 4.27.3
accelerate 0.17.1

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Reproduction

https://huggingface.co/stabilityai/stable-diffusion-2-inpainting
```
from diffusers import StableDiffusionInpaintPipeline
import time

time_without_safetensors = time.time()
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-inpainting",
    torch_dtype=torch.float16,
    use_safetensors=False
)
pipe.to("cuda")
print("without safetensors took", time.time() - time_without_safetensors)

time_with_safetensors = time.time()
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-inpainting",
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe.to("cuda")
print("with safetensors took", time.time() - time_with_safetensors)

```
Run the code once to fully download the models, if they dont exist.
Then:
First run, without safetensors 2.5s, with safetensors 20s (why?)
Second run, without safetensors 1.4s, with safetensors 1.4s.

### Expected behavior

Expected safetensors loading to be faster.

**Comment by Narsil** [comment]
I can't tell you without being able to reproduce:

```
without safetensors took 67.08731865882874
with safetensors took 38.6969056
```

Currently your script includes download times, which can highly vary for so many reasons.
Even excluding this, you have disk speed, which again depends highly on hardware and what you have been doing before (if the file is already in disk cache, then the OS will not have read the file from disk which is orders of magnitude faster)

And you also have cuda drivers initialization which is rather slow and will make whatever is the first example appear slower than the other. Here is what I'm seeing on second run:
```
without safetensors took 2.78419828414917
with safetensors took 1.5361552238464355
```

Try using the benchmarks if you want to bench, they are specifically made to avoid looking at those issues.
Still in the real world you might see all these things but there are something a library can do nothing for (disk reads are slow, cuda driver is slow, disk cache hit is not controllablee nor flushable).

I will close this, feel free to reopen if thereś more to it.
