### ISSUE TITLE
load incorrect weight values from a HF model on a big-endian machine

### ISSUE THREAD

**Issue by kiszk** [huggingface/safetensors#307]
### System Info

```
Python: 3.10
PyTorch: the latest main branch (i.e. 2.0.1+)
safetensor: 0.3.1
Platform: s390x (big-endian)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

Execute the following script on s390x after installing safetensor.

```
from transformers import AutoModelForSequenceClassification
torch.serialization.set_default_load_endianness(torch.serialization.LoadEndianness.LITTLE)
model = AutoModelForSequenceClassification.from_pretrained("roberta-base")
print(model.roberta.embeddings.position_embeddings.weight)
```

The output is 
```
Parameter containing:
tensor([[1.4715e-38, 1.7692e-38, 5.9353e-39,  ..., 8.8744e-39, 3.0194e-39,
         1.4712e-38],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [1.7637e-38, 1.7682e-38, 8.8821e-39,  ..., 2.9727e-39, 1.4779e-38,
         5.1024e-41],
        ...,
        [2.0658e-38, 1.4734e-38, 8.8287e-39,  ..., 5.2997e-41, 2.0663e-38,
         6.0351e-41],
        [1.4755e-38, 1.7712e-38, 2.0579e-38,  ..., 1.7650e-38, 2.0572e-38,
         5.9387e-39],
        [3.0012e-39, 1.7679e-38, 1.7633e-38,  ..., 2.0641e-38, 1.7639e-38,
         8.8477e-39]], requires_grad=True)
```

### Expected behavior

When I tried to execute an HF transformer model (i.e. little endian layout) with safetensor format on a big-endian machine, I met this issue.

When I execute the same script on s390x w/o installing safetensor.
```
from transformers import AutoModelForSequenceClassification
torch.serialization.set_default_load_endianness(torch.serialization.LoadEndianness.LITTLE)
model = AutoModelForSequenceClassification.from_pretrained("roberta-base")
print(model.roberta.embeddings.position_embeddings.weight)
```

The output is 
```
Parameter containing:
tensor([[-0.0115,  0.0204,  0.0197,  ...,  0.0050, -0.0274, -0.0439],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0346, -0.0169, -0.0895,  ..., -0.0542,  0.0291,  0.0173],
        ...,
        [ 0.1191, -0.0587, -0.0396,  ..., -0.0179,  0.1249,  0.0205],
        [ 0.0833, -0.0272, -0.0368,  ..., -0.0429,  0.1288, -0.0052],
        [ 0.0850,  0.2573, -0.1257,  ..., -0.0952,  0.1443, -0.0131]],
       requires_grad=True)
```

I expect this result even using safetensor format.

**Comment by Narsil** [comment]
First time I'm encountering a big endian machine.

For `torch` this lib is using https://pytorch.org/docs/stable/storage.html?highlight=from+storage#torch.UntypedStorage.from_file which allows for fast loading.

I don't seen any flags to specify endianness.

There are currently some protection to prevent *writing* a big endian file (for `numpy`).
I must say I'm not sure how `torch` handles endianness.

https://github.com/pytorch/pytorch/issues/101688

Would you happen to know any way I could emulate bigendianness or get easy access to such a machine ? (So I could fix those holes)

**Comment by kiszk** [comment]
[This](https://github.com/linuxone-community-cloud/technical-resources/blob/master/faststart/deploy-virtual-server.md) is a good document to get an access to s390x.

**Comment by kiszk** [comment]
To write a big endian file for pytorch is also prohibited.

```
$ cat st.py 
import safetensors
from safetensors.torch import save_file, load_file
import torch

tensors = {
   "a": torch.zeros((2, 3)),
   "b": torch.zeros((4, 5), dtype=torch.int16)
}

save_file(tensors, "./model.safetensors.s390x")

# Now loading
loaded = load_file("./model.safetensors.s390x")
print(loaded)
$ python st.py
Traceback (most recent call last):
  File "/home/ishizaki/PyTorch/tmp/st.py", line 10, in <module>
    save_file(tensors, "./model.safetensors.s390x")
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/safetensors/torch.py", line 232, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/home/ishizaki/PyTorch/.venv/lib/python3.10/site-packages/safetensors/torch.py", line 377, in _flatten
    raise ValueError("Big endian is not supported, serialization need to be in little endian")
ValueError: Big endian is not supported, serialization need to be in little endian
```

**Comment by akx** [comment]
> Would you happen to know any way I could emulate bigendianness or get easy access to such a machine ? (So I could fix those holes)

Another relatively easy way should probably be `qemu-system-s390x` with a Debian s390 live CD :)

**Comment by kiszk** [comment]
I will take a one-week vacation from Friday. I will respond slowly for a while.

**Comment by kiszk** [comment]
Now, I have been back from my vacation. I executed these two programs with 0.3.2. However, the results are not what I expected. Since I cannot reopen this issue, I will open a new issue and investigate the reason.
