### ISSUE TITLE
channels-last memory format

### ISSUE THREAD

**Issue by keturn** [huggingface/safetensors#308]
### Feature request

Support `channels_last` memory format. (And probably any other pytorch dense [memory format](https://pytorch.org/docs/stable/tensor_attributes.html#torch.memory_format)), i.e. `channels_last_3d.`)

### Motivation

I was working with the [tiny-sd](https://huggingface.co/segmind/tiny-sd) model and it refused to save with the "You are trying to save a non contiguous tensor" error.

Upon closer examination, while these tensors did fail the `tensor.is_contiguous()` test, they _pass_ with `tensor.is_contiguous(memory_format=torch.channels_last)`.

### Your contribution

I might be able to help with this. But it smells like the sort of thing that requires some modification to how types are represented, and that's not something I want to blunder through without guidance.

**Comment by Narsil** [comment]
Hmm `safetensors` doesn't have a concept of channels last or not. It's  a tensor of shape (N, C, H, W) or (N, H, W, C) but there are not semantics associated with it.

You can probably do `tensor.contiguous()` on your tensor.

`safetensors` is expecting to see C-format, little endian, formatted tensor. Anything else will be rejected.

I *think* `is_contiguous(memory_format=torch.channels_last) just means it's *not* contiguous, but it's ok because the shape (N, C, H, W) is a lie, and it's actually (N, H, W, C) and contiguous with that shape.
All pure guess, but you can probably  easily check.

We cannot do that in `safetensors` directly, because some non contiguous 4-rank tensors could exist and not be actual images.

**Comment by keturn** [comment]
Yes, as far as being a storage for a bunch of bytes in-memory-order goes, the data file doesn't know about NCHW or NHWC. Same data type, same number of elements, etc.

But when it comes to `safetensors.torch.save_model` being an attractive replacement for the [standard `torch.save`](https://pytorch.org/docs/stable/generated/torch.save.html#torch.save), it would be helpful to support torch's memory-format semantics where we can.

You've thoroughly documented [reasons to not support shared tensors](https://huggingface.co/docs/safetensors/torch_shared_tensors#why-are-shared-tensors-not-saved-in-safetensors), but those reasons mostly don't apply to memory format. (With the probable exception of the "not all frameworks support this" caveat.)

This _could_ be done at the application layer, with the application sticking memory-format information in `metadata` and wrapping their load function to handle that -- but since weights are often trained and used in different applications, it would be best for consistency if it were handled at the library level, as `torch.save` does.

**Comment by Narsil** [comment]
Can you please try and send a small reproducible script for this ?

I want to play around if `save_model` could work around that  (I don't think so, but maybe by playing around I'll find a way).
What's funny is that `save_model` should already force contiguousness: https://github.com/huggingface/safetensors/blob/main/bindings/python/py_src/safetensors/torch.py#L93

**Comment by keturn** [comment]
`force_contiguous` is on _by default?_ then it should have done, shouldn't it. hmm.

**Comment by keturn** [comment]
welp, that would  be because diffusers doesn't use `save_model`, it uses `save_file`. And the contiguous thing is only in one of those functions. https://github.com/huggingface/diffusers/blob/1a8843f93ec88585df18c895f0ec3d0914df8d10/src/diffusers/models/modeling_utils.py#L323

**Comment by Narsil** [comment]
Can you provide a small example so that I can reproduce and provide you a real fix ?

**Comment by keturn** [comment]
'''py
import diffusers, torch

pipeline = diffusers.StableDiffusionPipeline.from_pretrained(
    "segmind/tiny-sd", revision="2106049adda63c2798176bc395d03d52284bccde", dtype=torch.float16, device="cuda")

pipeline.save_pretrained("/tmp/save-destination", safe_serialization=True)
```

**Comment by sayakpaul** [comment]
It doesn't happen with the following:

```
from diffusers import StableDiffusionPipeline
import torch

pipeline = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", torch_dtype=torch.float16
).to("cuda")

pipeline.save_pretrained("/tmp/save-destination", safe_serialization=True)
```

(Just tested on Colab with a T4 GPU with all the latest stable PYPI installations of `transformer`, `accelerate`, `diffusers`.)

**Comment by keturn** [comment]
Dunno, for that you'd have to ask @harishsegmind and fellows at @segmind. I can only assume some part of their training pipeline put things in channels-last format for runtime efficiency.

But it's not necessary to second-guess their choices here. Specifying memory format is a thing you can do with torch.save. It is [useful](https://pytorch.org/blog/tensor-memory-format-matters/). Reducing obstacles for people switching from pickles to safetensors is good.

**Comment by Narsil** [comment]
`safetensors` is not `torch` specific. Using `safetensors.torch.save_model` will work. I don't think `diffusers` maintainers should care about non standard layout.
