### ISSUE TITLE
Failed to build safetensors

### ISSUE THREAD

**Issue by dawidkubicki** [huggingface/safetensors#314]
### System Info

Hi there!

While installing (pip install transformers) on macOS Ventura 13.4.1 and pip 23.2.1 got the below error:

ERROR: Failed building wheel for safetensors
Failed to build safetensors
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Reproduction

pip install transformers

### Expected behavior

Installing collected packages: tokenizers, tqdm, regex, pyyaml, psutil, packaging, numpy, fsspec, huggingface-hub, transformers, accelerate

**Comment by Narsil** [comment]
What's your python version ?

**Comment by dawidkubicki** [comment]
My version is Python 3.8.5.
I was able to fix issue by downgrading safetensors to 0.3.1, and then installing transformers :).

**Comment by Narsil** [comment]
MacOs x86 ?

**Comment by dawidkubicki** [comment]
> MacOs x86 ?

Yes

**Comment by Narsil** [comment]
https://pypi.org/project/safetensors/0.3.2/#files

**Comment by joshua-lawrence** [comment]
Getting the same error in a python:3.11.3 docker image.

**Comment by Narsil** [comment]
@joshua-lawrence Still mac ?

**Comment by Narsil** [comment]
For docker... 
```
$ docker run -it --entrypoint /bin/bash python:3.11.3
root@7c15eb535883:/# pip install safetensors
Collecting safetensors
  Downloading safetensors-0.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 7.8 MB/s eta 0:00:00
Installing collected packages: safetensors
Successfully installed safetensors-0.3.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
root@7c15eb535883:/#
```

Everything works fine..

**Comment by nullcode** [comment]
same here python:3.11.3 docker image. on mac ventura, fails building, looking for Rust compiler

**Comment by Narsil** [comment]
Hopefully this helps. I don't own a Ventura atm, so not sure why it's not picking up the universal variant... 

https://github.com/huggingface/safetensors/actions/runs/5798175401/job/15716213715

**Comment by Narsil** [comment]
Can you try again ? Packages are up now.

**Comment by SSabev** [comment]
Can confirm, happened to us just now. It's a docker deploy container running on Fargate. Also pinning back to the 0.3.1 version

**Comment by ppodolsky** [comment]
Have failed to build in `python:3.10-slim` Docker image, build requires Rust compiler (on aarch64 machine)
Fixed by pinning previous version in `requirements.txt`:
```
safetensors==0.3.1
```

**Comment by Narsil** [comment]
`aarch64` is coming, currently slowed down by  `PowerPC` which takes WAAAYYY too long: https://github.com/huggingface/safetensors/actions/runs/5793974915/job/15714308958

**Comment by SSabev** [comment]
> @SSabev can you share your env ? Fargate doesn't run MacOS 13..

Apologies, yes, it' a linux X86_64. Docker image we're using is 3.9-slim-buster

**Comment by SSabev** [comment]
@Narsil latest deploy actually went through fine with 0.3.2 so not sure if it was a caching issue on our side. You can ignore!

**Comment by Narsil** [comment]
Possibly a temporary caching issue in Fargate yes (if it received the sources wheel before the prebuilt one)

**Comment by adavis444** [comment]
@Narsil `PowerPC` timed out, which blocked the release of `aarch64` wheels

**Comment by Narsil** [comment]
I cut it for now: https://github.com/huggingface/safetensors/actions/runs/5805545266

I'm not sure why it's so slow, I'll skip the build for now because I really don't like manually building releases.
If you know of any trick to speed up building I'm taking it.

**Comment by Narsil** [comment]
I would very much like so, but the GH action we have for it is taking more than 6h, which is the GH action timeout, therefore it gets killed before it has a chance to finish the release.

I'm all ears if you have suggestions to improve/fix this release GH action: 
https://github.com/huggingface/tokenizers/blob/main/.github/workflows/python-release-extra.yml#L17-L40

QEMU was always slow, but it used to fit in a few hours (it takes 30mn for aarch and x390x).

I would really like to publish to ppc64le too, but I would also really like to avoid doing it manually, as I know it's error prone (and the process has to be reinvented for each release)

**Comment by mgiessing** [comment]
That is understandable - I'll try to have a look why it takes so much time and eventually times out. Usually the indicated ~30 minutes is what I also experienced in other projects.

**Comment by amankumarhal** [comment]
I came across this error "error: failed building wheel for safetensors failed to build safetensors error: could not build wheels for safetensors, which is required to install pyproject.toml-based projects"
Fixed it by installing from source on mac:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
pip install setuptools_rust    
add rust to env --> source "$HOME/.cargo/env" 
rustup target add x86_64-apple-darwin   
git clone https://github.com/huggingface/safetensors 
cd safetensors/bindings/python    
pip install -e .

**Comment by Narsil** [comment]
@amankumarhal What platform are you on ?

**Comment by amankumarhal** [comment]
Apple M2 Mac Pro, MacOS 13.4

**Comment by thomscode** [comment]
I'm running into this problem again:

Platform:
Apple M2 MBP, macOS 13.5
Docker Desktop

If I install using Python 3.11.4 installed on macOS, it works fine.
If I install using DockerHub image `python:3.11` (running `3.11.4`) I get the following error:
```bash
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects
```

I can work around it for now by installing `safetensors 0.3.2`, but `0.3.3` does not install on a `linux/arm64` Docker image.

**Comment by Narsil** [comment]
Conda ?

**Comment by ash1ni** [comment]
Hi!, I was installing safetensors version 0.4.5 for my project but encountered with the below error, I also have rust already installed in my system. 

Collecting safetensors>=0.4.1 (from transformers)
  Using cached safetensors-0.4.5.tar.gz (65 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Current python version I have in my system: 3.13

**Comment by miikatoi** [comment]
> Hi!, I was installing safetensors version 0.4.5 for my project but encountered with the below error, I also have rust already installed in my system.
> 
> Collecting safetensors>=0.4.1 (from transformers) Using cached safetensors-0.4.5.tar.gz (65 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [6 lines of output]
> 
> ```
>   Cargo, the Rust package manager, is not installed or is not on PATH.
>   This package requires Rust and Cargo to compile extensions. Install it through
>   the system's package manager or via https://rustup.rs/
> 
>   Checking for Rust toolchain....
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> 
> Current python version I have in my system: 3.13

Are you able to run `rustc` or `cargo` commands in the shell where you are installing from? Even if Rust is installed, it must be in the PATH to be accessible.

For me the issue was solved by calling `export PATH="/root/.cargo/bin:${PATH}"` first.

**Comment by ash1ni** [comment]
> > Hi!, I was installing safetensors version 0.4.5 for my project but encountered with the below error, I also have rust already installed in my system.
> > Collecting safetensors>=0.4.1 (from transformers) Using cached safetensors-0.4.5.tar.gz (65 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> > × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [6 lines of output]
> > ```
> >   Cargo, the Rust package manager, is not installed or is not on PATH.
> >   This package requires Rust and Cargo to compile extensions. Install it through
> >   the system's package manager or via https://rustup.rs/
> > 
> >   Checking for Rust toolchain....
> >   [end of output]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> > × Encountered error while generating package metadata. ╰─> See above for output.
> > note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> > Current python version I have in my system: 3.13
> 
> @ash1ni Are you able to run `rustc` or `cargo` commands in the shell where you are installing from? Even if Rust is installed, it must be in the PATH to be accessible.
> 
> For me the issue was solved by calling `export PATH="/root/.cargo/bin:${PATH}"` first.

Hi @miikatoi actually I fixed the issue rust was working fine actually issue was with python's version (I was using 3.12 and it was causing errors). Thanks to the community btw :)
