### ISSUE TITLE
Can't install newest version on MacOs M1

### ISSUE THREAD

**Issue by nilicaal** [huggingface/safetensors#316]
### System Info

- `transformers` version: 4.31.0
- Platform: macOS-13.4.1-arm64-arm-64bit
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Reproduction

pip3 install safetensors

This results in the newest version (0.3.2) being installed:

pip3 show safetensors

Name: safetensors
Version: 0.3.2
Summary: Fast and Safe Tensor serialization
Home-page: https://github.com/huggingface/safetensors
Author: 
Author-email: 
License: Apache License 2.0
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: 
Required-by: transformers

Then simply reproduce by doing:

python3                   
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import safetensors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/safetensors/__init__.py", line 5, in <module>
    from ._safetensors_rust import SafetensorError, deserialize, safe_open, serialize, serialize_file  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so' (no such file), '/opt/homebrew/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

### Expected behavior

What I'd expect is that it pulls an arm64 version of safetensors when installing transformers, but instead this is only the x86 version.

I installed this on my other M1 MacBook Pro yesterday and it worked fine then. Since the new release since then, it no longer works properly. Downgrading to version 0.3.1 did work:

pip3 install safetensors==0.3.1

Maybe this was expected behaviour, but it was not to me :)

**Comment by andregather** [comment]
yeah, I just start having this same issue this morning

**Comment by andrenatal** [comment]
yeah, I just start having this same issue this morning

**Comment by powderluv** [comment]
Same issue. Downstream [CI](https://github.com/nod-ai/SHARK/actions/runs/5803233967/job/15730953262?pr=1739) using latest safetensors breaks on M1/M2 

Workaround with 0.3.1
