### ISSUE TITLE
Add local file support for pytorch to safetensor python bindings

### ISSUE THREAD

**Issue by ChrisCates** [huggingface/safetensors#331]
### Feature request

Hey guys,

Noticed that in [convert.py](https://github.com/huggingface/safetensors/blob/main/bindings/python/convert.py) there was no support for local file conversions.

I am currently working on a pull request that supports local filesystems. Is this something you would accept into the codebase?

### Motivation

I do not want my work to be visible on a public repository.

### Your contribution

I am working on a PR. Just want to confirm you guys would be willing to accept something I send in.

For context, I've updated`convert.py` to support the following CLI flags:

```python
    parser.add_argument(
        "--model_id",
        nargs="?",
        type=str,
        default="",
        required=False,
        help="The name of the model on the hub to convert. E.g. `gpt2` or `facebook/wav2vec2-base-960h`",
    )
    parser.add_argument(
        "--model_path",
        nargs="?",
        type=str,
        default="",
        required=False,
        help="The path to a model if choosing to convert locally E.g. `/home/fortytwo/my-little-llm",
    )
    parser.add_argument(
        "--output_path",
        nargs="?",
        type=str,
        default="",
        required=False,
        help="The path to write the safetensor version of the model if choosing to convert locally E.g. `/home/fortytwo/my-little-llm/safetensors",
    )
```

**Comment by Narsil** [comment]
For local files have you tried

```
model = AutoModelForXXX.from_pretrained("...")
model.save_pretrained("...", safe_serialization=True)
```
?

Most of what this script does is actually creating the PR on the hub, which by definition doesn't exist for local folders.

**Comment by ChrisCates** [comment]
Oh my god. So sorry.
I just realized I need to use GPTQ. exllama only supports 4bit quantization using GPTQ.
Its just that GPTQ ends up in the safetensor format.

Leaving this script here in case anyone else makes the same mistake as me: https://github.com/PanQiWei/AutoGPTQ/blob/main/examples/quantization/basic_usage.py
