### ISSUE TITLE
Slow load weight values from a HF model on a big-endian machine with the latest code

### ISSUE THREAD

**Issue by kiszk** [huggingface/safetensors#333]
### System Info

Python: 3.10
PyTorch: the latest main branch (i.e. 2.0.1+)
safetensors: 0.3.3
Platform: s390x (big-endian)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

I executed the following code using 0.3.1 and 0.3.3, and w/o safetensors.

```
import time
import torch
from transformers import T5ForConditionalGeneration, AutoTokenizer
try:
    import safetensors 
    print("safetensors version:", safetensors.__version__)
except:
    print("safetensors not installed")
torch.serialization.set_default_load_endianness(torch.serialization.LoadEndianness.LITTLE)

model = "google/flan-t5-xxl"
tokenizer = AutoTokenizer.from_pretrained(model)
input_text = "The square root of x is the cube root of y. What is y to the power of 2, if x = 4?"
input = tokenizer(input_text, return_tensors="pt").input_ids

t0 = time.perf_counter()
#model = T5ForConditionalGeneration.from_pretrained(model, low_cpu_mem_usage=True, use_safetensors=False)
model = T5ForConditionalGeneration.from_pretrained(model, low_cpu_mem_usage=True, use_safetensors=True)
t1 = time.perf_counter()
print("load elapsed time:", t1-t0)
output = model.decoder.forward(input_ids=input)  ## intentionally use decoder.forward() instead of generate()
t2 = time.perf_counter()
print("forward elapsed time:", t2-t1)
```

Findings
- Old version (0.3.1) w/o swapping data is quite faster than 0.3.3 w/ swapping data, which we understand.
- 0.3.3 is a bit slow than `torch.load`, which implies we could have some room to improve.

The result is the best time of five tries after I downloaded model files into local file system.

```
$ python flan-t5.py 
safetensors not installed
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:21<00:00,  4.37s/it]
load elapsed time: 22.09646322298795
forward elapsed time: 1.4204098680056632
```

```
$ python flan-t5.py 
safetensors version: 0.3.3
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:25<00:00,  5.05s/it]
load elapsed time: 25.486608179984614
forward elapsed time: 1.4887599580106325
```

```
$ python flan-t5.py 
safetensors version: 0.3.1
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 35.73it/s]
load elapsed time: 0.37154227000428364
forward elapsed time: 1.1782474629580975
```

### Expected behavior

We expect that we can alleviate the overhead of swapping data. The overhead of 4x looks too large.

**Comment by Narsil** [comment]
It's kind of a given. You cannot possible memory map on different endianness machine, therefore load is going to be much slower.

I'm not sure what you expect here.
Feel free to have a look and see if there are optimizations to be had on the current code.

**Comment by kiszk** [comment]
I agree. Different endian machine has two extra works.

1. allocating new object
2. Swapping data

As you pointed out, we cannot avoid 1. I will investigate whether we have more rooms to optimize for alleviating amount of extra works.

**Comment by Narsil** [comment]
From my experience on loading code there several things you could try out.

1: Load order: Loading first ALL tensors on CPU, THEN sending to GPU can be faster. (maybe on big endian it's the opposite)
2: Measure how fast is torch.load, we could be in theory as fast as it (although I might not optimize this as much given that big endian are relatively rare tbh).
3: Load the safetensors with PURE torch code to iterate faster. https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282 . This code doesn't work on big endian ofc, but if you manage to make pure torch more efficient, I can translate that into rust super easily.

**Comment by kiszk** [comment]
Thank you for your suggestion. I made a mistake. Flan-UL2 does not use safetensors. So, I did experiments with Flan-T5. I updated the experimental results in the description, which includes your point 2. The safetensors is bit slow than `torch.load` (i.e. `use_safetensors=False`).

I will try your point 3.

**Comment by Narsil** [comment]
bit slow ? By how much what are the 2 numbers ?

**Comment by kiszk** [comment]
Sorry for confusing you. I compared 22.5 sec (`torch.load`) and 22.1 sec (0.3.3), which performs to swap data at data loading.

**Comment by kiszk** [comment]
For point 3, I added the swap function ([`byteswap()`](https://github.com/pytorch/pytorch/blob/v2.1.0-rc1/torch/storage.py#L267-L273)) into `create_tensor()`. Since this is not truly pure Python and depends on the latest Python version, I know this is not a final solution.

It seems that this `create_tensor()` function corresponds to [this Rust function](https://github.com/huggingface/safetensors/blob/main/bindings/python/src/lib.rs#L870). Can we do the similar action by using existing crate like [bswap](https://docs.rs/bswap/latest/bswap/)?

Any question/comments/suggestions are appreciated.

```
import time
import mmap
import torch
import json
import os
from transformers import AutoModelForCausalLM
from huggingface_hub import hf_hub_download


def load_file(filename, device):
    with open(filename, mode="r", encoding="utf8") as file_obj:
        with mmap.mmap(file_obj.fileno(), length=0, access=mmap.ACCESS_READ) as m:
            header = m.read(8)
            n = int.from_bytes(header, "little")
            metadata_bytes = m.read(n)
            metadata = json.loads(metadata_bytes)

    size = os.stat(filename).st_size
    storage = torch.ByteStorage.from_file(filename, shared=False, size=size).untyped()
    offset = n + 8
    return {name: create_tensor(storage, info, offset) for name, info in metadata.items() if name != "__metadata__"}


DTYPES = {"F32": torch.float32}
device = "cpu"


def create_tensor(storage, info, offset):
    dtype = DTYPES[info["dtype"]]
    shape = info["shape"]
    start, stop = info["data_offsets"]
    s = storage[start + offset : stop + offset]
    s.byteswap(dtype)  ## avaiable from 2.1.0-rc1
    return torch.asarray(s, dtype=torch.uint8).view(dtype=dtype).reshape(shape)


def main():
    model_name = "gpt2"
    filename = hf_hub_download(model_name, filename="model.safetensors")

    t0 = time.perf_counter()
    weights = load_file(filename, device)
    t1 = time.perf_counter()
    print("load_file elapsed time:", t1-t0)
    print(weights.keys())
    print("ln_f.bias[-1]", weights["ln_f.bias"][-1])

    t0 = time.perf_counter()
    model = AutoModelForCausalLM.from_pretrained(model_name, use_safetensors=False)
    t1 = time.perf_counter()
    print("from_pretrained elapsed time:", t1-t0)
    print("ln_f.bias[-1]", model.transformer.ln_f.bias[-1])

if __name__ == "__main__":
    main()
```

**Comment by Narsil** [comment]
You need to cast to proper dtype before using `byteswap`. Otherwise the byteswap is a no-op (since the storage is declared as raw bytes).

This is what bit me when I created `0.3.2` with the faulty version :).
Unfortunately the byteswap is likely to slow everything down.
