### ISSUE TITLE
aarch64 linux missing from 0.3.3 release

### ISSUE THREAD

**Issue by madhavajay** [huggingface/safetensors#346]
### System Info

The aarch64 linux releases of `safetensor` are missing.
https://pypi.org/project/safetensors/0.3.3/#files

These were available in previous versions.
<img width="635" alt="Screenshot 2023-08-25 at 5 02 01 pm" src="https://github.com/huggingface/safetensors/assets/2882739/5c993655-b2f0-4dc7-bc4f-b15828145b59">

Aarch64 linux is also used in docker containers running on Apple Silicon. The main issue here is that compilation requires the rust compiler which isn't super friendly for users and or our CI pipelines.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Reproduction

On arm64 run:
```
$ docker run -it python:3.11 bash
$ pip install safetensors==0.3.3
```

### Expected behavior

A binary wheel is available for aarch64 linux.

On arm64 run:
```
$ docker run -it python:3.11 bash
$ pip install safetensors==0.3.2 # works
```

**Comment by Narsil** [comment]
Do you mind trying : `pip install -U safetensors==0.3.3.post1`.

Release builds got so slow they don't finish anymore for some arch : https://github.com/huggingface/safetensors/actions/runs/5952077724

I just revamped the release builds yesterday from the ground up to use maturin instead which doesn't seem plagued by this.

If this works I'll include the missing arch from this build.

**Comment by Narsil** [comment]
(I just yanked `post.1` so no one else would use it as I change the build system extensively)

**Comment by greg1232** [comment]
This broke all of our builds.

**Comment by Narsil** [comment]
Can you try `pip install -U safetensors==0.3.3.post1` and try to help working around github runner throttling please? 

Whining is easy, fixing is harder, please help.

I don't own or run aarch64, finding a workaround to the release script (which worked for more than a year just fine) is just as displeasing to me than it is to you.

**Comment by thomscode** [comment]
I have the same issue on a project I'm on, but it only affects local dev. I tried `pip install -U safetensors==0.3.3.post1` this morning and it worked like a charm. 

What help do you need with the GitHub runners?

**Comment by Narsil** [comment]
@thomscode Thanks for the answer !

I need to know the builds actually work. I rewrote the entire build script cycle to avoid the issue, and the thing is very different. And although it "should" work, I prefer confirmation from users actually using those platforms before pushing on everyone's computer (because it's kind of messy to abort once done). Also because "it works on my computer" never works great :).

0.3.3 Should land on monday on those extra archs. (I just need a bit of time rechecking things too on my side inside the wheels and don't really have the time this weekend).

**Comment by thomscode** [comment]
@Narsil,

Sounds good, let me know if there’s anything I can to to help confirm what works and doesn’t for you.

**Comment by Narsil** [comment]
Okay issue should be fixed now. Can you confirm ?

Turns out I just bypassed the github throttling: https://github.com/huggingface/safetensors/actions/runs/5998397987/job/16267143556

**Comment by thomscode** [comment]
Confirmed, this is working now. Glad you were able to find the workaround!
