### ISSUE TITLE
Cannot use zero-copy for a model that is saved and loaded on big-endian machine

### ISSUE THREAD

**Issue by kiszk** [huggingface/safetensors#353]
### System Info

```
Python: 3.10
PyTorch: the latest main branch (i.e. 2.1.0-rc1)
safetensors: 0.3.3
Platform: s390x (big-endian)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

The following code with safetensors 0.3.3 takes about 1.75 sec. On the other hand, it with safetensors 0.3.1 (removed [endian guard](https://github.com/huggingface/safetensors/blob/v0.3.1/bindings/python/py_src/safetensors/torch.py#L376-L377)) takes about 0.13 sec.

This is that we cannot use zero-copy with safetensors 0.3.3 on big-endian platform. Safetensors 0.3.3 saves data in little-endian (i.e. `3f80 0000` for 1.0 in `mode.safetensor`) even on a big-endian machine. So, safetensors 0.3.3 requires swaps data at save and load.
On the other hand, safetensors 0.3.1 saves data in big-endian (i.e. `0000 803f` for 1.0) on a big-endian machine. Then, it is fast by using zero-copy.

```
import torch
import time
import safetensors
from safetensors import safe_open
from safetensors.torch import save_file
print("safetensors version:", safetensors.__version__)

tensors = {}
for i in range(0, 1024):
    tensors["weight" + str(i)] = torch.ones(1024,1024, dtype=torch.float)
save_file(tensors, "model.safetensors")

tensors = {}
print("START load")
t0 = time.perf_counter()
with safe_open("model.safetensors", framework="pt", device="cpu") as f:
   for key in f.keys():
       tensors[key] = f.get_tensor(key)
t1 = time.perf_counter()
print("END   load", t1 - t0)
```

`model.safetensors` with 0.3.1
```
od -x model.safetensors | tail -10
0254460 3635 3738 3638 382c 3432 3930 3737 3239
0254500 3932 5d7d 2c22 7765 6967 6874 3939 3922
0254520 3a7b 2264 7479 7065 223a 2246 3332 222c
0254540 2273 6861 7065 223a 5b31 3032 342c 3130
0254560 3234 5d2c 2264 6174 615f 6f66 6673 6574
0254600 7322 3a5b 3432 3930 3737 3239 3932 2c34
0254620 3239 3439 3637 3239 365d 7d7d 2020 2020
0254640 0000 803f 0000 803f 0000 803f 0000 803f
*
40000254640
```

`model.safetensors` with 0.3.3
```
od -x model.safetensors | tail -10
0254460 3635 3738 3638 382c 3432 3930 3737 3239
0254500 3932 5d7d 2c22 7765 6967 6874 3939 3922
0254520 3a7b 2264 7479 7065 223a 2246 3332 222c
0254540 2273 6861 7065 223a 5b31 3032 342c 3130
0254560 3234 5d2c 2264 6174 615f 6f66 6673 6574
0254600 7322 3a5b 3432 3930 3737 3239 3932 2c34
0254620 3239 3439 3637 3239 365d 7d7d 2020 2020
0254640 3f80 0000 3f80 0000 3f80 0000 3f80 0000
*
40000254640
```

### Expected behavior

We expect that both little and big-endian platforms can take advantages of zero-copy in safetensors as possible.

**Comment by kiszk** [comment]
One idea is to introduce "endian marker" into [header](https://huggingface.co/docs/safetensors/index#format). Then,

No data swap occur (can use zero-copy)
-- endians of "endian marker" and platform are the same
-- no "endian marker" (i.e. little-endian) on little-endian platform
data swap occurs (cannot use zero-copy)
-- endians of "endian marker" and platform different
-- no "endian marker" on big-endian platform

Other solutions can be possible.

**Comment by Narsil** [comment]
This contradicts the spec.
https://github.com/huggingface/safetensors#format

Saving in big endian was a bug, not a feature, there were active protections attempting to prevent doing it actually, not sure how it wasn't caught.

I'm sorry  but big endian machines are just not enough used to warrant zero-copy on them. It's much easier to force little endianness everywhere and be a bit slower on those machines.
It would also mean that every implementation would have to think before knowing what's the endianness, and therefore if zero-copy is possible or not.

`safetensors` was first and foremost created to be safe, the lack of ambiguity helps in that regard. The zero-copy is just an added bonus.

I'm going to close this, as saving in big endian is not something that will happen.
