### ISSUE TITLE
Is it possible to append to tensors along a primary axis?

### ISSUE THREAD

**Issue by nollied** [huggingface/safetensors#354]
### Feature request

it would be really cool to be able to append to a safetensor file so you can continue to add data along, say, a batch dimension

### Motivation

for logging data during train runs that can be visualized from an external tool. something like a live application that lazily loads the saved data. this is super useful for reinforcement learning

### Your contribution

i could submit a PR if necessary.

**Comment by Narsil** [comment]
Hey thanks. That's a cool idea that can already be somehow hacked if you need to (use space buffer to have extra room in the header for modifications and put your extended buffer as the last one. So you could keep appending)


However this feels like a large stretch from the intent of the format lib, I don't think we should have support.
