### ISSUE TITLE
Safe tensors cannot be easily freed!

### ISSUE THREAD

**Issue by RezaYazdaniAminabadi** [huggingface/safetensors#355]
### System Info

Hi, 

I am using the safetensors for loading Falcon-180B model. I am loading the ckpts one by one on CPU, and then try to remove the tensors by simply calling `del` function. However, I am seeing that CPU memory keeps increasing until it runs out of memory and system crashes (I am also calling `gc.collect()` after deleting tensors). Is there any good way to release the safetensor memory.
Thanks,
Reza

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Reproduction

```
from safetensors.torch import load_file
sd_ = load_file(ckpt_path)
lens = len(sd_.keys())
for _ in range(lens):
       data = sd_.popitem()
        del data
del sd_
gc.collect()
```

### Expected behavior

release the memory after calling `gc.collect()`

**Comment by Narsil** [comment]
It's using torch own internal there, nothing safetensors is responsible for.

Torch uses `UntypedStorage` to back the file up, meaning the entire file storage will be allocated regardless of how many tensors you clean (tensors are like pointers into the file if you will).

**Comment by RezaYazdaniAminabadi** [comment]
sounds good, then it might be an issue with my environment/torch version. BTW, I did load the checkpoints on all devices and take the portion that I need and that works fine and it does not run OOM, I only see the problem on CPU!

**Comment by huangqiaobo** [comment]
> It's using torch own internal there, nothing safetensors is responsible for.
> 
> Torch uses `UntypedStorage` to back the file up, meaning the entire file storage will be allocated regardless of how many tensors you clean (tensors are like pointers into the file if you will).

I also get this problem
do you kwnow how to clean the memory of UntypedStorage？
