### ISSUE TITLE
Loaded results are unordered

### ISSUE THREAD

**Issue by lniehaus** [huggingface/safetensors#357]
### System Info

System: Ubuntu 22.04.2 LTS
Python: 3.9.17
safetensors: 0.3.3

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

1) Create `OrderedDict`
2) Create `raw_bytes` by `safetensors.numpy.save`
3) Save `raw_bytes` from `OrderedDict` via `zipfile` into archive.zip 
4) Load archive.zip via `zipfile`
5) Load data via `safetensors.numpy.load`

# Code
```python
import safetensors.numpy
import zipfile
import numpy as np
import collections
import os


def create_archive(filename:str, data:collections.OrderedDict, name:str):
    raw_bytes = safetensors.numpy.save(data)

    if not os.path.isfile(filename):
        archive = zipfile.ZipFile(
            file=filename,
            mode="x",
            compression=zipfile.ZIP_STORED,
        )
        archive.writestr(str(0), raw_bytes)
        archive.close()

def read_archive(filename:str, name:str):
    archive_new = zipfile.ZipFile(
        file=filename,
        mode="r",
        compression=zipfile.ZIP_STORED,
    )
    data = safetensors.numpy.load(archive_new.read(name=name))
    return data

if __name__ == "__main__":

    # Ordered Demo Data
    name="0"
    filename = "archive.zip"
    data = collections.OrderedDict({
        "key0": np.random.rand(3,2),
        "key1": np.random.rand(3,2),
        "key2": np.random.rand(3,2),
        "key3": np.random.rand(3,2),
        "key4": np.random.rand(3,2),
        "key5": np.random.rand(3,2),
        "key6": np.random.rand(3,2),
        "key7": np.random.rand(3,2),
        "key8": np.random.rand(3,2),
        "key9": np.random.rand(3,2)
    })

    # Create Archive
    create_archive(filename=filename, data=data, name=name)

    # Read Archive
    data_new = read_archive(filename=filename, name=name)

    print("data.keys()", data.keys())
    print("data_new.keys()", data_new.keys())

```

# Output
```
data.keys() odict_keys(['key0', 'key1', 'key2', 'key3', 'key4', 'key5', 'key6', 'key7', 'key8', 'key9'])
data_new.keys() dict_keys(['key1', 'key6', 'key5', 'key0', 'key2', 'key8', 'key9', 'key3', 'key7', 'key4'])
```

### Expected behavior

I would have expected that loading data results in the same order as it is written, but the order gets lost in the process.
This is because `safetensors.numpy.load` loads the data in a `Dict`. https://github.com/huggingface/safetensors/blob/main/bindings/python/py_src/safetensors/numpy.py#L80

By utilizing `OrderedDict` the order could be preserved.
The use case I am facing is saving layer weights from a neural network, where the order represents the training graph.
A workaround for my use case is to save the order as well and then sort it, but it seems to me that a preserved order might be useful for multiple use cases.

Is there a reason why `Dict` is used instead of `OrderedDict` ?

**Comment by sparverius** [comment]
I am interested in having ordered keys as well ... internally safetensors is written in rust and the passed in dict from python gets converted into a rust HashMap which does not preserve order...

upon further investigation, there seems to be no way to guarantee both efficiency & key order on the rust end 😞

> This is because safetensors.numpy.load loads the data in a Dict.
> https://github.com/huggingface/safetensors/blob/main/bindings/python/py_src/safetensors/numpy.py#L80

Note: [Changed in version 3.7: Dictionary order is guaranteed to be insertion order.](https://docs.python.org/3/library/stdtypes.html#:~:text=Changed%20in%20version%203.7:%20Dictionary%20order%20is%20guaranteed%20to%20be%20insertion%20order.)

> A workaround for my use case is to save the order as well and then sort it, but it seems to me that a preserved order might be useful for multiple use cases.

Agreed, for individual use cases saving the keys & sorting might be the best choice

If one desired to embed the information into the safetensors, at first glance a potential (naiive) solution could look something like: 

```python
import np
import safetensors

# naiive hardcoded approach ...

def save_ordered(tensors: Dict[str, np.ndarray], metadata: Optional[Dict[str, str]] = None) -> bytes:
    tensors = {f'{i}#{k}': v for i, (k, v) in enumerate(tensors.items())}
    return safetensors.numpy.save(tensors, metadata=metadata)

def load_ordered(data: bytes) -> Dict[str, np.ndarray]:
    loaded = safetensors.numpy.load(data)
    loaded = dict(sorted(loaded.items()))
    loaded = {''.join(k.split("#")[1:]): v for k, v in loaded.items()}
    return loaded
```

Though, on a testable scale it might be difficult to validate/track which models were or were not ordered this way... for using safetensors in leu of other pickling techniques, such as the example you give above, errors wouldn't be to difficult to navigate... however for loading the statedict of a model checkpoint with hundreds of layers where names are meaningful, I suspect a full validating solution, without compromising the current library, would require significantly more cohesion than the above magic hackery 🤖...

Hope you or others find this useful!

**Comment by Narsil** [comment]
Can you share a bit as to why you care about key order and what's the actual underlying issue  ?

What is it preventing you to do ? What would it enable  ?

**Comment by adonath** [comment]
>Can you share a bit as to why you care about key order and what's the actual underlying issue ?

I encountered the same issue. I was using `safetensors` to record the forward pass of a network to disk (think a forward hook in pytoch). Once I reload the data the order is lost, however the order of the intermediate results is relevant for debugging.
