### ISSUE TITLE
Format selection for saving quantized weights (bitsandbyres.nf4, SpQR etc)

### ISSUE THREAD

**Issue by poedator** [huggingface/safetensors#358]
### Feature request

Hi!
I am working on code to save models in quantized formats like `nf4` from [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) and [SpQR](https://github.com/Vahe1994/SpQR) (see my [PR in transformers](https://github.com/huggingface/transformers/pull/26037)). . Both these formats require storing multiple tensors per weight and also some hyperparameters. 

Could the Safetensors team suggest preferred way to save all this stuff in ST format? The choices that I see are:
for tensor types: 
	- save weights, scales, zeros etc as separate tensors using some nested naming scheme
	- pack into some king of structrue and serialize as one big tensor?  https://gist.github.com/poedator/81c3564ec548ef2992282d59447cacff
for hyperparameters:
	- save as _metadata_ components
	- serialize and save as tensors
	- pack hyperparameters into (protobuf? MsgPack? Json?) and save as single tensor
	- pack tensors + hyperparameters into one big structure and save as single tensor.

I see that similar matters are already raised here for other quantisation methods, including #256. It would be nice to have some universal way to store quantized weights.

Also it would be nice for ST to support not just tensors, but all other formats supported by `serde`

### Motivation

consistent representation of saved quantized weights

### Your contribution

ready to make a PR once there is guidance from the maintainers
@Narsil  ?

**Comment by akx** [comment]
I think #389 is related.
