### ISSUE TITLE
Memory is not deallocated after `safetensors.torch.load_file` is executed

### ISSUE THREAD

**Issue by Curt-Park** [huggingface/safetensors#369]
### System Info

```bash
- `transformers` version: 4.30.2
- Platform: Linux-5.15.0-82-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

```python
import tracemalloc
import psutil
import os
import gc
from safetensors.torch import load_file

f = open("tracemalloc_lora.txt", "w")
process = psutil.Process()
tracemalloc.start()

for i in range(10000):
    tracemalloc.reset_peak()

    model_path: str = f"lora.safetensors"
    load_file(model_path)  # HERE!!
    size, peak = tracemalloc.get_traced_memory()
    log = f"iter {i+1}: current size: {size}, peak size: {peak}, threshold: {gc.get_threshold()}, cnt: {gc.get_count()}, mem: {process.memory_info().rss}\n"
    print(log)
    f.write(log)

tracemalloc.stop()
f.close()
```

Command:
```bash
PYTHONMALLOC=malloc python test_lora.py
```
- log: [tracemalloc_lora.txt](https://github.com/huggingface/safetensors/files/12916956/tracemalloc_lora.txt)

From the log, you can see the memory footprint gradually increases during 10,000 iterations.
The memory leak is caused by `f.get_tensor(k)` in `load_file` function.

```python
def load_file(filename: Union[str, os.PathLike], device="cpu") -> Dict[str, torch.Tensor]:
    """
    Loads a safetensors file into torch format.

    Args:
        filename (`str`, or `os.PathLike`):
            The name of the file which contains the tensors
        device (`Dict[str, any]`, *optional*, defaults to `cpu`):
            The device where the tensors need to be located after load.
            available options are all regular torch device locations

    Returns:
        `Dict[str, torch.Tensor]`: dictionary that contains name as key, value as `torch.Tensor`

    Example:

    ```python
    from safetensors.torch import load_file

    file_path = "./my_folder/bert.safetensors"
    loaded = load_file(file_path)
    ```
    """
    result = {}
    with safe_open(filename, framework="pt", device=device) as f:
        for k in f.keys():
            result[k] = f.get_tensor(k)  # <---- HERE!! if you remove this line, the memory leak disappears.
    return result
```

### Expected behavior

Here is the log that `result[k] = f.get_tensor(k)` is commented out. There is no leak. (10,000 iterations)

[tracemalloc_lora.txt](https://github.com/huggingface/safetensors/files/12917313/tracemalloc_lora.txt)

**Comment by Curt-Park** [comment]
On the other hand, the following way doesn't cause memory leaks:
```python
from safetensors.torch import load

model_path = "model_manager_profiler/weights/lora/12/lora.safetensors"
with open(model_path, "rb") as model:
    data = model.read()
    loaded = load(data)
```

- log: [tracemalloc_lora.txt](https://github.com/huggingface/safetensors/files/12917410/tracemalloc_lora.txt) (10,000 iterations)

**Comment by harupy** [comment]
Encountered the same issue.

**Comment by ddh0** [comment]
I think I'm encountering this issue. My script is getting killed by OOM when it shouldn't be

**Comment by joe-zxh** [comment]
> On the other hand, the following way doesn't cause memory leaks:
> 
> from safetensors.torch import load
> 
> model_path = "model_manager_profiler/weights/lora/12/lora.safetensors"
> with open(model_path, "rb") as model:
>     data = model.read()
>     loaded = load(data)
> * log: [tracemalloc_lora.txt](https://github.com/huggingface/safetensors/files/12917410/tracemalloc_lora.txt) (10,000 iterations)

@Curt-Park 
thanks for your code, the memory leak is disappeared.

However, this method is much slower than the load_file function, here is my result.

<html xmlns:x="tencent"><meta charset="utf-8"><style type='text/css'></style><body>
  | 325MB Lora | 6.64G SDXL model | memory leak?
-- | -- | -- | --
load_file | 0.02s | 0.023s | yes
safetensors.torch.load | 0.15s | 2.5s | no
torch.load pth | 0.07s | 0.82s | no

</body></html>
