### ISSUE TITLE
Big-endian or Little-endian, Row-first or Column-first undocumented in specification.

### ISSUE THREAD

**Issue by norlesh** [huggingface/safetensors#370]
### Feature request

'specification' fails to document the byte order (big-endian v little-endian) of each tensor element or the element order (row-first v column-first) when serializing the tensors in the byte buffer section of the output file (I would classify this as a bug in the original specification of the file format).

### Motivation

For the file format to be re-implemented on another platform these parameters need to be specified otherwise there are at least four potential ways to interpret the tensor bytes in the .safetensor file with only one producing the intended result. 

### Your contribution

no

**Comment by Narsil** [comment]
The spec IS the README.
