### ISSUE TITLE
How do I load the tensors in Rust? 

### ISSUE THREAD

**Issue by arunpatro** [huggingface/safetensors#375]
Hi, 

I am unable to find good documentation to read the weights in rust. I want to write gpt2 from scratch, and want to be able to load the HF weights. Since, I only plan to use the ndarray library, I want to be able to load the FP32 tensors somehow. Please help. 

In python I do:
```python
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM
import safetensors

tokenizer = AutoTokenizer.from_pretrained("gpt2")
model = AutoModelForCausalLM.from_pretrained("gpt2")
safetensors.torch.save_model(model, 'gpt2_weights.st')
```

I want to use some code like this in rust (which is currently incorrect because safetensors doesn't have a Reader) and I am unable to figure out the API.
```rust
use safetensors::Reader;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let reader = Reader::from_file("gpt2_weights.st")?;

    for (name, tensor) in reader.tensors() {
        println!("Tensor name: {}", name);
        let tensor = tensor?;
        println!("Shape: {:?}", tensor.shape());        
    }

    Ok(())
}
```

**Comment by rockerBOO** [comment]
I'd also like some more info about this as well. I have been trying to deconstruct the tests to get an idea how to get the dtype'd tensor in the rust side.

https://github.com/huggingface/safetensors/blob/86e356fed6b75d4b0a06ee446ab94f1317eafc2e/safetensors/src/tensor.rs#L390-L428 This may have some hints about it. The data comes as u8 which then needs to be converted to the dtype (which is in the tensor metadata). That should get the resulting tensor in proper data type. But i couldn't wrap together enough code to get it working.

**Comment by arunpatro** [comment]
Please share if you get this working! I tried to look at the candle codebase, maybe we can look at these tests -> https://github.com/huggingface/candle/blob/main/candle-core/src/safetensors.rs

**Comment by rockerBOO** [comment]
For my use cases I have the following loading from a buffer (for use in WASM specifically). 

```rust
use candle_core::{DType, Device, Tensor};
use safetensors::tensor::TensorView;
use safetensors::{tensor::TensorInfo, Dtype, SafeTensorError, SafeTensors};

// Some are not supported in candle_core
pub fn into_dtype(dtype: Dtype) -> DType {
    match dtype {
        Dtype::F32 => DType::F32,
        // Dtype::F16 => DType::F16,
        // Dtype::BOOL => DType::BOOL,
        Dtype::U8 => DType::U8,
        // Dtype::I8 => DType::I8,
        // Dtype::I16 => DType::I16,
        // Dtype::U16 => DType::U16,
        // Dtype::BF16 => DType::,
        Dtype::I32 => DType::I64,
        Dtype::U32 => DType::U32,
        Dtype::F64 => DType::F64,
        Dtype::I64 => DType::I64,
        // Dtype::U64 => DType::U64,
        _ => todo!(),
    }
}

// Probably not efficient to move from the tensor view into the raw buffer here
pub fn from_tensor_view(t: &TensorView) -> Result<Tensor, candle_core::Error> {
    Tensor::from_raw_buffer(t.data(), into_dtype(t.dtype()), t.shape(), &Device::Cpu)
}

fn from_tensor_views(tensors: Vec<TensorView>) -> Vec<Tensor> {
    tensors
        .iter()
        .filter_map(|t| from_tensor_view(t).ok()) // Drops invalid here, be aware
        .collect()
}

// SafeTensors crate has a read metadata from buffer but not in candle_core that I could find
fn get_metadata() -> Result<HashMap<String, String>, SafeTensorError>{
     let (_size, metadata) = SafeTensors::read_metadata(buffer)?;

    metadata.metadata().to_owned().ok_or_else(|| {
        SafeTensorError::IoError(io::Error::new(
            io::ErrorKind::InvalidData,
            "invalid metadata",
        ))
    })
}
```

Candle core also has a [safetensors entry](https://docs.rs/candle-core/latest/candle_core/safetensors/fn.load_buffer.html).

I tried to use just the safetensors crate but the amount of code in candle core to convert over the different types was a little beyond the amount of time I could look into it. I think the tradeoff was OK, added about 130KB to my WASM file but I didn't have to write out all conversions and I get tensor calculation support. No WebGPU support yet it seems so just CPU (as to why the device is just CPU there).

Maybe some simple conversion could be possible without requiring a crate here or maybe a better way of converting it over would be adequate. Works OK for my use case. Thanks for pointing out this option.

**Comment by Narsil** [comment]
Solutions seems fine, not the most efficient but that's ok given the issue is in candle requiring a copy (because it requires ownership).

As a backnote, safetensors only exposes `[u8]` because dtypes require alignement, which byte buffer don't therefore it's easier to work with any alignment exposing pure bytes, and only make alignement as an optimization trick to do actual zero-copy (which is what is done for PyTorch for instance).
