### ISSUE TITLE
Get the scaler value of a 0-dim PySafeSlice

### ISSUE THREAD

**Issue by yunfeng-scale** [huggingface/safetensors#380]
### Feature request

When using `f.get_slice()` to load a slice, if this variable is 0-dim, there doesn't seem to be a way to extract its value (or maybe there is, in this case please comment and close the ticket).

### Motivation

This is a bit annoying that data needs to be loaded again with f.get_tensor() to get its value.

### Your contribution

Not right now

**Comment by Narsil** [comment]
Can you provide a reproducible example of the failure ?

There shouldn't be any problem with 0-dim tensors, but since the properties rely on the underlying libs it's hard to tell what's failing for you.

**Comment by fxmarty-amd** [comment]
+1, `param = param[:]` is failing.

**Comment by ArthurZucker** [comment]
Actually just got the same issue with: `tests/models/speecht5/test_modeling_speecht5.py::SpeechT5ForSpeechToTextTest::test_can_use_safetensors` ! The proposed fix is working
