### ISSUE TITLE
Would a CLI to perform convert operation be useful?

### ISSUE THREAD

**Issue by remyleone** [huggingface/safetensors#381]
### Feature request

Could it be possible to add to this repo a CLI tool that would use the library to convert files stored in different format and convert them to safetensors.
It would be useful to have also from the command line a way to introspect a model and find some property about it (layers, metadata, ...)

### Motivation

I'm frustrated when I got a lot of example models on my disk that I'm not too sure about and I would like to have a quick and easy way from the command line to inspect them, convert them, compress them and do all the tasks I need to perform straight from the command line with completion support.

### Your contribution

I could contribute design suggestions about the interface but I have no particular knowledge of Rust and I'm learning transformers and ML in general.

**Comment by Narsil** [comment]
Something like that : https://github.com/huggingface/safetensors/blob/main/bindings/python/convert.py ?
