### ISSUE TITLE
[Structural] Dtypes supported in safetensors.

### ISSUE THREAD

**Issue by Narsil** [huggingface/safetensors#389]
The goal of this document is to try and explain the design decisions behind Dtypes acceptance in `safetensors`.

# Obvious inclusions

Dtypes which have intrinsics on multiple platforms (GPU, CPU) and have clean specification like f32 (https://ieeexplore.ieee.org/document/30711) are an obvious support.
Some DTypes are slightly more exotic, yet supported natively more recently specifically for ML workloads and do make them an obvious choice.

- `blfloat16` : https://en.wikipedia.org/wiki/Bfloat16_floating-point_format
- `fp8` https://arxiv.org/abs/2209.05433 (Nvidia, Arm, intel). (So actually fp8_e4m3 and fp8_e5m2)

# Obvious rejections

Anything that is custom to a single app, not widely used, with no intrinsics support are obviously not going to be included.
The goal of a common shared tensor format is to clarify the contents of a given file, make them easy to load and undertand runtime costs associated with using such files, accepting arbitrary data types hurt those properties.

# Harder decisions

Some dtypes are harder to decide. For instance `complex64` and ggml's `QX_Y_Z` k_quants. Or even `int4` (which doesn't exist as such but is implied by models compressed with GPTQ or AWQ compressions).
There are several things to consider:

- **No intrinsics**, means they have no actual hardware support, so users depend on librairies to implement operations for those custom dtypes to be able to use said tensors.
- **Wideness of support**. Some dtypes might get more libraries support like complex64 being in tensorflow, torch, numpy vs GGML dtype which is supported only in a single one. Numpy also seems to be the only one with `complex256`.
- **Dtype complexity**. This one is a pretty big one. ComplexN seem like relatively simple dtypes, they share the same properties as most other classical dtypes regarding alignment/shape/slicing. They are effectively just pairs of those simpler dtypes and therefore require just a 2 factor in most places. But `int4` or `QX_Y_Z` pose entirely different challenges in that regard. Since those dtypes do NOT have intrinsics support, it means they must be modified in order to get used and a whole lot of issues come with that. Can you slice into it ? (Mostly no, expect if you're at some nice borders of the dtype). What is the alignment expectation ? That alignement will usually break the zero-copy property. For instance if you try to shard a given model into 4 Tensor Parallel shard, which is somewhat common for large models, then on GPTQ/AWQ models you might come across issues when the TP boundary is within a given `int32` (would happen less frequently with u8 but would still happen). That means special logic has to be applied and copies have to occur to provide the users with the tensor slices they asked for. This is not an implementation problem as it's easy to do, but a usability issue, where this non zero-copy behavior is unpredictable.
- **Widespread support**. Finally one big aspect to consider is the practicality for dtypes. DTypes that have barely any use in the context of ML, also have little impact in being supported in `safetensors`. For instance `complex64` is a super niche dtype and I don´t think any widespread models currently uses it. On the other had, GPTQ/Q_X_Y_Z are already extremely widely used and therefore might merit more attention, to make those easier to use for the community at large.
- ** Longterm maintenance** A final aspect is that any dtype that gets added in `safetensors` will get very longterm support. There is no plan ever to make breaking changes to the format, therefore inclusions can never be removed. If some dtypes are added at a particular time, and they fall out, then maintenance still has to be applied regardless to the fact that they have fallen out of hype. This could present the risk of hindering the development of the format by making it too much of a burden to add things in the future.

At this point I am not attempting to make a clear cut on what gets to go in or not, it's more a call to advice on how to create a good, sound and maintenable decision boundary, clearly explanable to external contributors that might like their favorite format to be added in.

**Comment by sluijs** [comment]
If the goal of safetensors remains to be a zero-copy format, I would refrain from adding _any_ dtype that breaks this property. Once you go down that road, the format will become more unpredictable, and one might argue that you could add any compressed tensor representation that becomes popular in the future. 

An alternative option would be to create an external crate that converts an arbitrary (popular) format into something that's compatible with safetensors in its current state.
