### ISSUE TITLE
Integer overflow (32-bit) when saving large tensor on Windows

### ISSUE THREAD

**Issue by turboderp** [huggingface/safetensors#391]
### System Info

Windows 10 Pro 22H2 64-bit (also confirmed on Windows 11)
Python 3.11.4
safetensors 0.4.0
numpy 1.26.2
torch 2.1.1+cu118

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

```python
import torch
from safetensors.torch import save_file
filename = "E:\Temp\test.safetensors"
test_tensor = torch.randn((32, 2048, 64000), dtype=torch.half, device="cuda:0")  # device="cpu" also fails
save_file({ "test_tensor": test_tensor }, filename)
```

### Expected behavior

Expected to create .safetensors file with a size of about 8GB, containing a single tensor. Instead, fails with the error:

```
Traceback (most recent call last):
  File "C:\Sync\Dev2\test.py", line 6, in <module>
    save_file({ "test_tensor": test_tensor }, filename)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\safetensors\torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\safetensors\torch.py", line 475, in _flatten
    return {
           ^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\safetensors\torch.py", line 479, in <dictcomp>
    "data": _tobytes(v, k),
            ^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\safetensors\torch.py", line 421, in _tobytes
    data = np.ctypeslib.as_array(newptr, (total_bytes,))  # no internal copy
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\ctypeslib.py", line 521, in as_array
    p_arr_type = ctypes.POINTER(_ctype_ndarray(obj._type_, shape))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\ctypeslib.py", line 354, in _ctype_ndarray
    element_type = dim * element_type
                   ~~~~^~~~~~~~~~~~~~
ValueError: Array length must be >= 0, not -201326592
```

The reported array length is exactly `2 * (test_tensor.numel() - 2**32)`, leading me to suspect this is an integer overflow issue. The issue only seems to manifest on Windows, with the code above performing as expected on Linux.

**Comment by Narsil** [comment]
Definitely looks like an overflow for Windows.

Can you make sure you're running on 64bit execution mode and not 32 ? (For instance isolating the python code that's being called and checking `total_bytes` value.

**Comment by turboderp** [comment]
So I've investigated it a bit. As far as I can tell, I'm running in 64-bit mode, and there should be no way for Python to load a 32-bit version of numpy.

```python
import sys
import platform
import numpy.distutils.system_info as sysinfo
print(sys.maxsize)
print(platform.architecture()) 
print(sysinfo.platform_bits)
```

Yields `9223372036854775807`, `('64bit', 'WindowsPE')` and `64`, respectively.

I can narrow the error down to the following line in torch.py:

```python
length = int(np.prod(tensor.shape).item())
```

Specifically it's the `np.prod` function that returns a negative value. According to the [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.prod.html), the accumulator for the `prod` function should use the same datatype as the input array, but maybe that's not entirely accurate? In any case, this is one way to fix it:

```python
length = int(np.prod(tensor.shape, dtype=np.uint64).item())
```

It does look like something somewhere is defaulting to a 32-bit mode (although you'd think then it would overflow to a negative value at 2**31, or to a small positive value at 2**32), but I'm not sure what other tests I could run.
