### ISSUE TITLE
"metadata-generation-failed" when installing in Termux

### ISSUE THREAD

**Issue by FindingMeaning** [huggingface/safetensors#405]
![Screenshot_20231216-092018~3.png](https://github.com/huggingface/safetensors/assets/146155413/85ac81a3-9e50-4dbb-ab00-46e73c3f1c8b)

```
~ $ pip install safetensors                          Collecting safetensors
  Using cached safetensors-0.4.1.tar.gz (62 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-38lcmxhq', '--interpreter', '/data/data/com.termux/files/usr/bin/python3.11']' died with <Signals.SIGSEGV: 11>.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /data/data/com.termux/files/usr/tmp/pip-modern-metadata-38lcmxhq --interpreter /data/data/com.termux/files/usr/bin/python3.11`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Android version:
10

Kernel build information:
Linux localhost 4.4.192-perf+ #1 SMP PREEMPT Fri Nov 5 12:30:40 CST 2021 aarch64 Android

**Comment by Narsil** [comment]
Android ??

You need to install cargo first if you want to build from source (which is what the wheel is trying to do here)
https://www.rust-lang.org/tools/install

Sorry we don' t prepackage this particular arch it seems (I'm wondering which arch it is though because aarch64 is )

**Comment by FindingMeaning** [comment]
I'm using Termux on Android and there is no error with safetensors. The error was caused as by default Termux uses different file system layout than usual linux, running `termux-chroot` ( which setup a chroot to mimic a normal Linux file system ) before using pip to install safetensors fixed everything.
Here is the proof that i managed to install it :-
https://www.reddit.com/r/termux/comments/18ojp5j/how_to_install_sentencetransformers_with_all/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

**Comment by FindingMeaning** [comment]
I'm really sorry I forgot to tell that I fixed the error.

**Comment by Narsil** [comment]
Thanks for sharing your solution here.

**Comment by Abhisak522** [comment]
Mera code banaya kudu ko Kam nahin kar rahe code isliye Kam nahin kar raha kyunki code galat bola hai kot color banae lekin condom galat pade Hain
