### ISSUE TITLE
Does safetensors save the model's hierarchical structure? Is it similar to ONNX?

### ISSUE THREAD

**Issue by ZDragonX** [huggingface/safetensors#407]
If safetensors saves the model's hierarchical structure, how can one access this structure? Is it possible to read it directly like with ONNX?Can I directly load a model from safetensors? 
If the hierarchical structure of the model is not preserved, does it mean that the original model must be read from config.json?

**Comment by Narsil** [comment]
No it does not, safetensors saves only tensors, not the associated graph structure to do inference on it.
