### ISSUE TITLE
`HeaderTooLarge` error for smaller than 100MB headers

### ISSUE THREAD

**Issue by apolinario** [huggingface/safetensors#414]
### System Info

safetensors==0.4.1

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Reproduction

File to download: https://huggingface.co/minimaxir/sdxl-ugly-sonic-lora/resolve/main/pytorch_lora_weights.bin?download=true

```py
from safetensors.torch import load_file
lora_state_dict = load_file("pytorch_lora_weights.bin")
```

Errors with 
```shell
    308     with safe_open(filename, framework="pt", device=device) as f:
    309         for k in f.keys():
    310             result[k] = f.get_tensor(k)

SafetensorError: Error while deserializing header: HeaderTooLarge
```

### Expected behavior

According to 
https://github.com/huggingface/safetensors/blob/a2afb0a78636a542fbd2ffab5b4a9886c8b29ad8/safetensors/src/tensor.rs#L22

This error should only take place if the header is > 100Mo, however the entire LoRA has 23.48MB so it is unlikely the header is >100Mo

**Comment by julien-c** [comment]
but that's not a safetensors file you're loading, no?

**Comment by apolinario** [comment]
It indeed is not, it is a `*.bin` pytorch file, although I have done this process of loading `*.bin` pytorch files with the safetensors library as a form a way to "auto-convert" before and it does work in some cases 🤔 for example for textual embeddings in pytorch format: https://huggingface.co/fofr/sdxl-2004/blob/main/embeddings.pti - so I may have wrongly assumed it would work in all cases? 

If that's not intended behavior/if this shouldn't work (loading a pytorch file and have it auto-convert to safetensors) - maybe the error should be more descriptive? (e.g.: "You tried to load a non-safetensors file")

**Comment by Narsil** [comment]
That's becuase: https://huggingface.co/fofr/sdxl-2004/blob/main/embeddings.pti IS a safetensors despite the naming

If you want to "convert" you need:

```python
weights = torch.load(filename)
save_file(weights, safetensors_filename)
```

(Caveats may apply depending on how odd those tensors are, but in most cases it should just work)
