### ISSUE TITLE
Support multi-device loading for load_file() with pt framework

### ISSUE THREAD

**Issue by mobicham** [huggingface/safetensors#477]
### Feature request

Support automatically loading tensors to the same devices used during serialization. 

### Motivation

Safetensors `load_file` only supports single device dispatching, defaulting to the 'cpu'. On the other hand, `torch.load` supports loading each tensor directly to the same device that was used at the time of serialization, which is actually the default desired behavior (`map_location=None`). When dealing with tensors dispatched on multiple devices, `torch.load` is much more efficient and easier to use. 

### Your contribution

NaN

**Comment by AAnirudh07** [comment]
+1 to this, would be super helpful!
