### ISSUE TITLE
misleading error message in `safe_open`

### ISSUE THREAD

**Issue by Clement-Lelievre** [huggingface/safetensors#485]
### System Info

safetensors 0.4.3

- `transformers` version: 4.39.3
- Platform: Linux-5.15.0-1048-aws-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.23.1
- Safetensors version: 0.4.3
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Reproduction

1. `mkdir some_folder/`
2. safe_open("some_folder", "pt")

this produces the error `OSError: No such device (os error 19)`

### Expected behavior

instead of an error mentioning a missing device, it should say that the path passed does not point to a safetensors file, or am I missing something?

**Comment by julien-c** [comment]
thanks for reporting @Clement-Lelievre

**Comment by lonngxiang** [comment]
same error

**Comment by jiahuanluo** [comment]
It appears that safetensors model files stored in certain mounted directories, such as Ceph, may encounter this issue. Copying the model to the local hard drive (" ~/ ") allows it to load correctly. Additionally, saving it as a .bin model file does not encounter this issue.
Maybe the same problem [here](https://github.com/huggingface/transformers/issues/25179)

**Comment by yaogang2060** [comment]
same here. change ckpt_path to **.safetensors file path** not folder path is all right.
