### ISSUE TITLE
README is inaccurate

### ISSUE THREAD

**Issue by judahrand** [huggingface/safetensors#487]
### System Info

NA

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Reproduction

The README states that Arrow requires decoding and then links to a page which is about Parquet (which does require decoding). Arrow and Parquet are two independent formats. Arrow's IPC format is not the same as Parquet. Could this be corrected?

### Expected behavior

The README should refer to the Arrow format. The point about lack of (native)`bf16` support is, I believe, still valid but the point about requiring decoding doesn't hold water I don't think.

**Comment by julien-c** [comment]
maybe cc @lhoestq too

**Comment by lhoestq** [comment]
Arrow doesn't require decoding indeed, I opened https://github.com/huggingface/safetensors/pull/488 to fix this passage in the readme
