### ISSUE TITLE
How to save model checkpoint from a distributed training from multiple nodes?

### ISSUE THREAD

**Issue by Emerald01** [huggingface/safetensors#490]
Hello, 

When I use accelerator and deepspeed Zero3 to train the model in one node with 8 GPUs, the following code smoothly saves the model checkpoint
```
ds_state_dict = model._zero3_consolidated_16bit_state_dict() # here model is sharded 

if self.accelerator.is_main_process:
    save_file(ds_state_dict, f"{output_dir}/full_model.safetensors")
```
However, when I move the code to two nodes with each node 8 GPUs, this code does not work.
The error is like:

```Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.```

Then I thought maybe I should not call main process only because there are two nodes, so I call the local rank 0 to save
```
ds_state_dict = model._zero3_consolidated_16bit_state_dict() # here model is sharded 

if self.accelerator.local_process_index == 0:
    save_file(ds_state_dict, f"{output_dir}/full_model.safetensors")

```

And the error becomes:
```
save_file(ds_state_dict, f"{output_dir}/full_model.safetensors")
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 284, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 457, in _flatten
    raise ValueError(f"Expected a dict of [str, torch.Tensor] but received {type(tensors)}")
ValueError: Expected a dict of [str, torch.Tensor] but received <class 'NoneType'>

```
I am not sure in this case, what is the right way to use safetensors to save?

**Comment by Narsil** [comment]
Hi, 

I am not well versed in Deepspeed, but the error probably lies with them (or in your code and understanding of what's possible).
```python
ValueError: Expected a dict of [str, torch.Tensor] but received <class 'NoneType'>
```

Seems quite explicit to me, `ds_state_dict` is `None` and therefore cannot be saved.
Why it's None, I do not know.

I'm closing this since the issue seems to be elsewhere than this library.
