### ISSUE TITLE
cannot import name 'save_open' from 'safetensors'

### ISSUE THREAD

**Issue by sun2ot** [huggingface/safetensors#536]
### System Info

- python 3.9.20
- safetensors 0.4.5 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Reproduction

I tried `pip install safetensors` and `conda install -c huggingface safetensors`. 

Other API such as `safetensors.torch.save_file/load_file` are correct as the docs described. 

But can not use `save_open` from `from safetensors import save_open`

### Expected behavior

```python
from safetensors import safe_open

tensors = {}
with safe_open("model.safetensors", framework="pt", device=0) as f:
    for k in f.keys():
        tensors[k] = f.get_tensor(k)
```

**Comment by kalvdans** [comment]
Please check your spelling of `safe_open`, if you still get an error, please post your error message.

**Comment by sun2ot** [comment]
Sorry, I think it may be due to a caching issue. I was unable to import safe_open earlier, but after trying again, it returned to normal.
