### ISSUE TITLE
Question about determinism across multiple saves

### ISSUE THREAD

**Issue by iNeil77** [huggingface/safetensors#66]
Hello, thanks for this initiative!

I have faced hashing/comparison problems with pickle as the serialized output is known to be non-deterministic for the same object (e.g. dictionaries with the same items but with different insert histories). Does this library (and its associated format) provide a guarantee regarding the serialization being deterministic for the same input?

**Comment by Narsil** [comment]
This library now does order keys on save.

This is not a promise of the spec though, so don't necessarily expect it when reading files.

**Comment by iNeil77** [comment]
Got it. Thanks!
