### ISSUE TITLE
Support for model streaming (disk -> VRAM)?

### ISSUE THREAD

**Issue by Xyem** [huggingface/safetensors#67]
Would it be possible (if it isn't already) for this format to support streaming from disk? Having to load the entire model into RAM, only to pass it off to the GPU, causes tools that use it to require considerable amounts of RAM, but only for small windows of time.

In memory-tight situations (e.g. VMs) being able to stream from disk would reduce model load time (due to avoiding hitting swap) and out-of-memory errors when multiple model changes are done (less opportunity for memory leaks).

**Comment by Narsil** [comment]
Hi @Xyem , it's already the case if you use `SAFETENSORS_FAST_GPU=1` environement variable.

This will skip entirely allocating on CPU (well the file will be memory mapped so expect some allocation, but not all).

Then you only need to do 

```python
from safetensors import safe_open

with safe_open("model.safetensors", framework="pt", device="cuda") as f:
    tensor = f.get_tensor("mytensor")
```

the reason for the environment variable, is that the current code has to do some unsafe things. They should be safe as it simply calls `cudaMemcpy` directly for you, but it hasn't had enough scrutiny yet to be sure it's safe.

**Comment by Xyem** [comment]
That's amazing and will make using these models so much smoother for me. Thank you!

**Comment by oovm** [comment]
What is the equivalent operation in the rust api? 

I can't find the Reader, only deserialize.

**Comment by oovm** [comment]
@Narsil I want to know if there is a [Read](https://doc.rust-lang.org/std/io/trait.Read.html) interface on rust side that can act on a large file on disk.

The required memory space is `max(sizeof(tensor))` instead of `sum(sizeof(tensor))`

**Comment by Narsil** [comment]
@oovm deserialize is what you are looking for.
Personally, in my pure rust approach, I do the memmap2 on my client to prevent allocations

Implementing a `Read` is definitely doable, but I feel like it might be not ideal when reading specific tensors with a lot of skips on the file (where as memmap does it transparently).

I added an example here: https://github.com/huggingface/safetensors/pull/189 Would that work ?

**Comment by oovm** [comment]
Good idea, I forgot mmap, it works better.

**Comment by Narsil** [comment]
Closing the issue then, feel free to reopen.
