### ISSUE TITLE
Get rid of pyO3, use `ctypes` + C FFI

### ISSUE THREAD

**Issue by KOLANICH** [huggingface/safetensors#73]
Getting rid of pyO3 and using `ctypes` instead will allow to
* get rid of the requirement of having and executing Rust compiler in order to build a wheel;
* reduce bloat by reusing the shared library

**Comment by Narsil** [comment]
That's not going to happen.

The very goal of using rust is to prevent ANY out of bounds calls, which are super easy to trigger in C or `ctypes`. I actually managed to trigger some out of bounds with buggy code when loading tensors slices.

If you want pure python, there's no need for ctypes actually: https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282
If you want to implement something with ctypes, feel free to do so, but this won't be the case here.

**Comment by Narsil** [comment]
https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282

**Comment by KOLANICH** [comment]
>https://gist.github.com/Narsil/3edeec2669a5e94e4707aa0f901d2282

Thanks, a good example to craft an own implementation.

>If you want pure python, there's no need for ctypes actually:

I want to

1. get rid of the inconvenient build dependencies for the Python part: pyO3 and Rust toolchain.
2. achieve independence on python interpreter version
3. achieve reuse of the shared lib
