### ISSUE TITLE
Don't panic, use `NotImplementedError`

### ISSUE THREAD

**Issue by KOLANICH** [huggingface/safetensors#76]
1. it is semantically incorrect
2. A dirty workaround has to be used, since `pyo3_runtime.PanicException` cannit be imported since `pyo3_runtime` is not a real module.

```python
def getPanicExceptionType():
    try:
        safetensors.safetensors_rust.serialize({"tensor_name": {"dtype": "test", "shape": [0, 0], "data": b""}}, None)
    except BaseException as ex:
        return ex.__class__

PanicException = getPanicExceptionType()
```

**Comment by Narsil** [comment]
Very correct !

Currently this lib outputs Exception a bit everywhere without careful consideration for the Exception type.

Anyhow, here is the fix: https://github.com/huggingface/safetensors/pull/78
