### ISSUE TITLE
Decide whether `float128` and the complex types should be implemented

### ISSUE THREAD

**Issue by KOLANICH** [huggingface/safetensors#77]
* [ ] `g` float128
* [ ] `D` complex128
* [ ] `G` complex256
* [ ] `F` complex64

**Comment by Narsil** [comment]
Happy to add support for all of these.

The only requirement for it would be to have at least 1 framework between `torch` , `flax`, `tensorflow` that support them.

**Comment by KOLANICH** [comment]
Why doesn't `numpy` count?

**Comment by Narsil** [comment]
I'm very biased towards ML and more precisely deep learning which mostly uses those 3. 

But you're actually right `numpy` should be ok. Using those types will limit usage with the 3 above, but it shouldn't the file's business.
