### ISSUE TITLE
State an official extension shorter than `.safetensors`

### ISSUE THREAD

**Issue by KOLANICH** [huggingface/safetensors#85]
`sftr` seems to be used by noone.

**Comment by julien-c** [comment]
what's wrong with a long file extension? On the hf Hub we use `.safetensors` to detect if a model contains safetensors weights (e.g. https://huggingface.co/facebook/bart-base), so it's quite convenient for us to just keep this one
<img width="1359" alt="Screenshot 2022-11-17 at 19 38 07" src="https://user-images.githubusercontent.com/326577/202530410-b468531e-4c6f-4574-a3f8-ae41c11e897c.png">

**Comment by KOLANICH** [comment]
It is too long. I guess you can change the configs in HF Hub to detect `sftr` too.

**Comment by Narsil** [comment]
You are free to use any extension you want. This is not enforced anywhere by any means.

Let's keep this open and see if others in the community agree on this.
